-- Tier 3 city batch seed: Medellín, Guadalajara, Santiago, Lima (Expanded to 20 checkpoints per city)
-- Additive and re-runnable. Apply manually in Supabase SQL Editor.
-- Fix: Included mandatory task strings to satisfy NOT NULL constraints.

insert into public.city_packs (slug, name, route_note, finish_label, safety_note, is_active)
values
  ('medellin', 'Medellín', 'Comunas, valley crossings, and Antioquia metro towns across the Medellín region.', 'Medellín Tier 3 sheet complete.', 'Ride inside local laws, watch hills and valley traffic, and keep checkpoints public.', true),
  ('guadalajara', 'Guadalajara', 'Colonias, metropolitan plazas, and Jalisco municipalities around Guadalajara.', 'Guadalajara Tier 3 sheet complete.', 'Ride inside local laws, stay alert in central plazas, and use public routes.', true),
  ('santiago', 'Santiago', 'Comunas, cordillera edges, and central valley municipalities around Santiago.', 'Santiago Tier 3 sheet complete.', 'Ride inside local laws, respect cycle lanes, and keep every stop public.', true),
  ('lima', 'Lima', 'Distritos, coastal cliffs, and central Lima metropolitan areas.', 'Lima Tier 3 sheet complete.', 'Ride inside local laws, stay predictable in heavy traffic, and use public approaches.', true)
on conflict (slug) do update
set
  name = excluded.name,
  route_note = excluded.route_note,
  finish_label = excluded.finish_label,
  safety_note = excluded.safety_note,
  is_active = excluded.is_active,
  updated_at = now();

with pack_refs as (
  select id, slug from public.city_packs where slug in ('medellin', 'guadalajara', 'santiago', 'lima')
)
insert into public.city_checkpoints (
  pack_id,
  slug,
  name,
  lat,
  lng,
  district,
  category,
  vibe,
  hint,
  task_local,
  task_fast,
  task_chaotic,
  sort_weight,
  is_active
)
values
  -- Medellín
  ((select id from pack_refs where slug = 'medellin'),'medellin-el-poblado','El Poblado',6.210000,-75.567000,'Comuna 14','district','straightforward','El Poblado is a central district hub.','Ride to El Poblado and confirm the public approach.','Use the direct safe route to El Poblado and keep moving.','Check the nearest safe corner at El Poblado and continue.',10,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-la-candelaria','La Candelaria',6.251000,-75.568000,'Comuna 10','district','straightforward','La Candelaria is the historic center.','Ride to La Candelaria and confirm the public approach.','Use the direct safe route to La Candelaria and keep moving.','Check the nearest safe corner at La Candelaria and continue.',20,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-laureles','Laureles',6.244000,-75.589000,'Comuna 11','district','straightforward','Laureles is a major residential district.','Ride to Laureles and confirm the public approach.','Use the direct safe route to Laureles and keep moving.','Check the nearest safe corner at Laureles and continue.',30,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-san-javier','San Javier',6.253000,-75.586000,'Comuna 13','district','straightforward','San Javier is a key hillside district.','Ride to San Javier and confirm the public approach.','Use the direct safe route to San Javier and keep moving.','Check the nearest safe corner at San Javier and continue.',40,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-belen','Belén',6.232000,-75.596000,'Comuna 16','district','straightforward','Belén is a major valley district.','Ride to Belén and confirm the public approach.','Use the direct safe route to Belén and keep moving.','Check the nearest safe corner at Belén and continue.',50,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-envigado','Envigado',6.175000,-75.584000,'Envigado','municipality','straightforward','Envigado is a major municipality south of Medellín.','Ride to Envigado and confirm the public approach.','Use the direct safe route to Envigado and keep moving.','Check the nearest safe corner at Envigado and continue.',60,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-itagui','Itagüí',6.172000,-75.613000,'Itagüí','municipality','straightforward','Itagüí is an industrial municipality hub.','Ride to Itagüí and confirm the public approach.','Use the direct safe route to Itagüí and keep moving.','Check the nearest safe corner at Itagüí and continue.',70,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-bello','Bello',6.333000,-75.558000,'Bello','municipality','straightforward','Bello is a major municipality north of Medellín.','Ride to Bello and confirm the public approach.','Use the direct safe route to Bello and keep moving.','Check the nearest safe corner at Bello and continue.',80,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-sabaneta','Sabaneta',6.151000,-75.615000,'Sabaneta','municipality','straightforward','Sabaneta is a small, vibrant municipality hub.','Ride to Sabaneta and confirm the public approach.','Use the direct safe route to Sabaneta and keep moving.','Check the nearest safe corner at Sabaneta and continue.',90,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-la-estrella','La Estrella',6.158000,-75.643000,'La Estrella','municipality','straightforward','La Estrella is the southernmost metro town.','Ride to La Estrella and confirm the public approach.','Use the direct safe route to La Estrella and keep moving.','Check the nearest safe corner at La Estrella and continue.',100,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-copacabana','Copacabana',6.347000,-75.509000,'Copacabana','municipality','straightforward','Copacabana is a northern valley hub.','Ride to Copacabana and confirm the public approach.','Use the direct safe route to Copacabana and keep moving.','Check the nearest safe corner at Copacabana and continue.',110,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-girardota','Girardota',6.376400,-75.447300,'Girardota','municipality','straightforward','Girardota is a satellite town in the north.','Ride to Girardota and confirm the public approach.','Use the direct safe route to Girardota and keep moving.','Check the nearest safe corner at Girardota and continue.',120,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-barbosa','Barbosa',6.438800,-75.334100,'Barbosa','municipality','straightforward','Barbosa is the northernmost satellite of the metro area.','Ride to Barbosa and confirm the public approach.','Use the direct safe route to Barbosa and keep moving.','Check the nearest safe corner at Barbosa and continue.',130,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-guarne','Guarne',6.280000,-75.442700,'Guarne','municipality','straightforward','Guarne is a major satellite on the eastern plateau.','Ride to Guarne and confirm the public approach.','Use the direct safe route to Guarne and keep moving.','Check the nearest safe corner at Guarne and continue.',140,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-rionegro','Rionegro',6.155000,-75.388900,'Rionegro','municipality','straightforward','Rionegro is the secondary metro hub east of the city.','Ride to Rionegro and confirm the public approach.','Use the direct safe route to Rionegro and keep moving.','Check the nearest safe corner at Rionegro and continue.',150,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-la-ceja','La Ceja',6.010800,-75.427500,'La Ceja','municipality','straightforward','La Ceja is a peaceful satellite town in the east.','Ride to La Ceja and confirm the public approach.','Use the direct safe route to La Ceja and keep moving.','Check the nearest safe corner at La Ceja and continue.',160,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-marinilla','Marinilla',6.170900,-75.334200,'Marinilla','municipality','straightforward','Marinilla is a historic satellite town on the highway.','Ride to Marinilla and confirm the public approach.','Use the direct safe route to Marinilla and keep moving.','Check the nearest safe corner at Marinilla and continue.',170,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-caldas','Caldas',6.090000,-75.637500,'Caldas','municipality','straightforward','Caldas is the southern gateway satellite.','Ride to Caldas and confirm the public approach.','Use the direct safe route to Caldas and keep moving.','Check the nearest safe corner at Caldas and continue.',180,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-san-cristobal','San Cristóbal',6.278800,-75.637300,'San Cristóbal','corregimiento','straightforward','San Cristóbal is a western hillside district.','Ride to San Cristóbal and confirm the public approach.','Use the direct safe route to San Cristóbal and keep moving.','Check the nearest safe corner at San Cristóbal and continue.',190,true),
  ((select id from pack_refs where slug = 'medellin'),'medellin-santa-elena','Santa Elena',6.210500,-75.498400,'Santa Elena','corregimiento','straightforward','Santa Elena is the flower-growing rural district.','Ride to Santa Elena and confirm the public approach.','Use the direct safe route to Santa Elena and keep moving.','Check the nearest safe corner at Santa Elena and continue.',200,true),

  -- Guadalajara
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-centro-historico','Centro Histórico',20.677000,-103.347000,'Guadalajara','district','straightforward','Centro Histórico is the heart of the city.','Ride to Centro Histórico and confirm the public approach.','Use the direct safe route to Centro Histórico and keep moving.','Check the nearest safe corner at Centro Histórico and continue.',10,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-zapopan','Zapopan',20.722000,-103.391000,'Zapopan','municipality','straightforward','Zapopan is a major metro municipality.','Ride to Zapopan and confirm the public approach.','Use the direct safe route to Zapopan and keep moving.','Check the nearest safe corner at Zapopan and continue.',20,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-tlaquepaque','Tlaquepaque',20.640000,-103.310000,'Tlaquepaque','municipality','straightforward','Tlaquepaque is a historic metro municipality.','Ride to Tlaquepaque and confirm the public approach.','Use the direct safe route to Tlaquepaque and keep moving.','Check the nearest safe corner at Tlaquepaque and continue.',30,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-providencia','Providencia',20.695000,-103.385000,'Guadalajara','district','straightforward','Providencia is a major residential and commercial district.','Ride to Providencia and confirm the public approach.','Use the direct safe route to Providencia and keep moving.','Check the nearest safe corner at Providencia and continue.',40,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-chapultepec','Chapultepec',20.674000,-103.368000,'Guadalajara','street','straightforward','Chapultepec is a vibrant metro corridor.','Ride to Chapultepec and confirm the public approach.','Use the direct safe route to Chapultepec and keep moving.','Check the nearest safe corner at Chapultepec and continue.',50,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-tonala','Tonalá',20.624000,-103.242000,'Tonalá','municipality','straightforward','Tonalá is a municipality known for its crafts.','Ride to Tonalá and confirm the public approach.','Use the direct safe route to Tonalá and keep moving.','Check the nearest safe corner at Tonalá and continue.',60,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-tlajomulco','Tlajomulco',20.474000,-103.446000,'Tlajomulco','municipality','straightforward','Tlajomulco is a major southern satellite municipality.','Ride to Tlajomulco and confirm the public approach.','Use the direct safe route to Tlajomulco and keep moving.','Check the nearest safe corner at Tlajomulco and continue.',70,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-el-salto','El Salto',20.517000,-103.181000,'El Salto','municipality','straightforward','El Salto is an industrial satellite municipality.','Ride to El Salto and confirm the public approach.','Use the direct safe route to El Salto and keep moving.','Check the nearest safe corner at El Salto and continue.',80,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-ixtlahuacan','Ixtlahuacán',20.350000,-103.195000,'Ixtlahuacán','municipality','straightforward','Ixtlahuacán is a satellite town near Chapala.','Ride to Ixtlahuacán and confirm the public approach.','Use the direct safe route to Ixtlahuacán and keep moving.','Check the nearest safe corner at Ixtlahuacán and continue.',90,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-juanacatlan','Juanacatlán',20.499000,-103.149000,'Juanacatlán','municipality','straightforward','Juanacatlán is a satellite town on the river.','Ride to Juanacatlán and confirm the public approach.','Use the direct safe route to Juanacatlán and keep moving.','Check the nearest safe corner at Juanacatlán and continue.',100,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-chapala','Chapala',20.297000,-103.189000,'Chapala','municipality','straightforward','Chapala is the main lakeside satellite town.','Ride to Chapala and confirm the public approach.','Use the direct safe route to Chapala and keep moving.','Check the nearest safe corner at Chapala and continue.',110,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-ajijic','Ajijic',20.299000,-103.258000,'Chapala','town','straightforward','Ajijic is a major lakeside satellite community.','Ride to Ajijic and confirm the public approach.','Use the direct safe route to Ajijic and keep moving.','Check the nearest safe corner at Ajijic and continue.',120,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-jocotepec','Jocotepec',20.286000,-103.430000,'Jocotepec','municipality','straightforward','Jocotepec is the western lakeside satellite.','Ride to Jocotepec and confirm the public approach.','Use the direct safe route to Jocotepec and keep moving.','Check the nearest safe corner at Jocotepec and continue.',130,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-tequila','Tequila',20.883000,-103.837000,'Tequila','municipality','straightforward','Tequila is the historic satellite town of the spirit.','Ride to Tequila and confirm the public approach.','Use the direct safe route to Tequila and keep moving.','Check the nearest safe corner at Tequila and continue.',140,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-tala','Tala',20.658000,-103.704000,'Tala','municipality','straightforward','Tala is a western satellite town.','Ride to Tala and confirm the public approach.','Use the direct safe route to Tala and keep moving.','Check the nearest safe corner at Tala and continue.',150,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-zapotlanejo','Zapotlanejo',20.620000,-103.067000,'Zapotlanejo','municipality','straightforward','Zapotlanejo is an eastern satellite town.','Ride to Zapotlanejo and confirm the public approach.','Use the direct safe route to Zapotlanejo and keep moving.','Check the nearest safe corner at Zapotlanejo and continue.',160,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-tesistan','Tesistán',20.785000,-103.475000,'Zapopan','town','straightforward','Tesistán is a northern satellite town in Zapopan.','Ride to Tesistán and confirm the public approach.','Use the direct safe route to Tesistán and keep moving.','Check the nearest safe corner at Tesistán and continue.',170,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-santa-anita','Santa Anita',20.548000,-103.447000,'Tlaquepaque','town','straightforward','Santa Anita is a southern satellite town in Tlaquepaque.','Ride to Santa Anita and confirm the public approach.','Use the direct safe route to Santa Anita and keep moving.','Check the nearest safe corner at Santa Anita and continue.',180,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-el-fortin','El Fortín',20.628000,-103.468000,'Zapopan','district','straightforward','El Fortín is a western residential satellite.','Ride to El Fortín and confirm the public approach.','Use the direct safe route to El Fortín and keep moving.','Check the nearest safe corner at El Fortín and continue.',190,true),
  ((select id from pack_refs where slug = 'guadalajara'),'guadalajara-bugambilias','Bugambilias',20.608000,-103.465000,'Zapopan','district','straightforward','Bugambilias is an upscale southern residential district.','Ride to Bugambilias and confirm the public approach.','Use the direct safe route to Bugambilias and keep moving.','Check the nearest safe corner at Bugambilias and continue.',200,true),

  -- Santiago
  ((select id from pack_refs where slug = 'santiago'),'santiago-centro','Santiago Centro',-33.437000,-70.650000,'Santiago','district','straightforward','Santiago Centro is the historic city center.','Ride to Santiago Centro and confirm the public approach.','Use the direct safe route to Santiago Centro and keep moving.','Check the nearest safe corner at Santiago Centro and continue.',10,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-las-condes','Las Condes',-33.413000,-70.566000,'Las Condes','district','straightforward','Las Condes is a major business and residential district.','Ride to Las Condes and confirm the public approach.','Use the direct safe route to Las Condes and keep moving.','Check the nearest safe corner at Las Condes and continue.',20,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-providencia','Providencia',-33.432000,-70.615000,'Providencia','district','straightforward','Providencia is a central commercial district.','Ride to Providencia and confirm the public approach.','Use the direct safe route to Providencia and keep moving.','Check the nearest safe corner at Providencia and continue.',30,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-nunoa','Ñuñoa',-33.454000,-70.597000,'Ñuñoa','district','straightforward','Ñuñoa is a major residential and cultural hub.','Ride to Ñuñoa and confirm the public approach.','Use the direct safe route to Ñuñoa and keep moving.','Check the nearest safe corner at Ñuñoa and continue.',40,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-vitacura','Vitacura',-33.398000,-70.589000,'Vitacura','district','straightforward','Vitacura is a premium residential district.','Ride to Vitacura and confirm the public approach.','Use the direct safe route to Vitacura and keep moving.','Check the nearest safe corner at Vitacura and continue.',50,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-maipu','Maipú',-33.510000,-70.757000,'Maipú','municipality','straightforward','Maipú is a historic metropolitan municipality.','Ride to Maipú and confirm the public approach.','Use the direct safe route to Maipú and keep moving.','Check the nearest safe corner at Maipú and continue.',60,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-colina','Colina',-33.200000,-70.670000,'Colina','municipality','straightforward','Colina is a northern satellite town.','Ride to Colina and confirm the public approach.','Use the direct safe route to Colina and keep moving.','Check the nearest safe corner at Colina and continue.',70,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-lampa','Lampa',-33.280000,-70.880000,'Lampa','municipality','straightforward','Lampa is a northern satellite municipality.','Ride to Lampa and confirm the public approach.','Use the direct safe route to Lampa and keep moving.','Check the nearest safe corner at Lampa and continue.',80,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-til-til','Til Til',-33.080000,-70.930000,'Til Til','municipality','straightforward','Til Til is a northern rural satellite town.','Ride to Til Til and confirm the public approach.','Use the direct safe route to Til Til and keep moving.','Check the nearest safe corner at Til Til and continue.',90,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-buin','Buin',-33.730000,-70.740000,'Buin','municipality','straightforward','Buin is a southern satellite town.','Ride to Buin and confirm the public approach.','Use the direct safe route to Buin and keep moving.','Check the nearest safe corner at Buin and continue.',100,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-paine','Paine',-33.810000,-70.740000,'Paine','municipality','straightforward','Paine is a major southern satellite town.','Ride to Paine and confirm the public approach.','Use the direct safe route to Paine and keep moving.','Check the nearest safe corner at Paine and continue.',110,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-talagante','Talagante',-33.660000,-70.930000,'Talagante','municipality','straightforward','Talagante is a major southwestern satellite hub.','Ride to Talagante and confirm the public approach.','Use the direct safe route to Talagante and keep moving.','Check the nearest safe corner at Talagante and continue.',120,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-penaflor','Peñaflor',-33.610000,-70.880000,'Peñaflor','municipality','straightforward','Peñaflor is a southwestern satellite town.','Ride to Peñaflor and confirm the public approach.','Use the direct safe route to Peñaflor and keep moving.','Check the nearest safe corner at Peñaflor and continue.',130,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-el-monte','El Monte',-33.680000,-70.980000,'El Monte','municipality','straightforward','El Monte is a rural southwestern satellite town.','Ride to El Monte and confirm the public approach.','Use the direct safe route to El Monte and keep moving.','Check the nearest safe corner at El Monte and continue.',140,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-melipilla','Melipilla',-33.690000,-71.220000,'Melipilla','municipality','straightforward','Melipilla is the western satellite town.','Ride to Melipilla and confirm the public approach.','Use the direct safe route to Melipilla and keep moving.','Check the nearest safe corner at Melipilla and continue.',150,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-san-jose','San José de Maipo',-33.640000,-70.350000,'San José de Maipo','municipality','straightforward','San José de Maipo is a mountain satellite town.','Ride to San José de Maipo and confirm the public approach.','Use the direct safe route to San José de Maipo and keep moving.','Check the nearest safe corner at San José de Maipo and continue.',160,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-puente-alto','Puente Alto',-33.616000,-70.575000,'Puente Alto','municipality','straightforward','Puente Alto is a major metropolitan hub in the south.','Ride to Puente Alto and confirm the public approach.','Use the direct safe route to Puente Alto and keep moving.','Check the nearest safe corner at Puente Alto and continue.',170,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-la-florida','La Florida',-33.522000,-70.598000,'La Florida','municipality','straightforward','La Florida is a major metropolitan hub in the east.','Ride to La Florida and confirm the public approach.','Use the direct safe route to La Florida and keep moving.','Check the nearest safe corner at La Florida and continue.',180,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-san-bernardo','San Bernardo',-33.592000,-70.705000,'San Bernardo','municipality','straightforward','San Bernardo is a southern metropolitan hub.','Ride to San Bernardo and confirm the public approach.','Use the direct safe route to San Bernardo and keep moving.','Check the nearest safe corner at San Bernardo and continue.',190,true),
  ((select id from pack_refs where slug = 'santiago'),'santiago-pudahuel','Pudahuel',-33.445000,-70.760000,'Pudahuel','municipality','straightforward','Pudahuel is a major western metropolitan hub.','Ride to Pudahuel and confirm the public approach.','Use the direct safe route to Pudahuel and keep moving.','Check the nearest safe corner at Pudahuel and continue.',200,true),

  -- Lima
  ((select id from pack_refs where slug = 'lima'),'lima-miraflores','Miraflores',-12.122000,-77.030000,'Miraflores','district','straightforward','Miraflores is the primary coastal district center.','Ride to Miraflores and confirm the public approach.','Use the direct safe route to Miraflores and keep moving.','Check the nearest safe corner at Miraflores and continue.',10,true),
  ((select id from pack_refs where slug = 'lima'),'lima-san-isidro','San Isidro',-12.096000,-77.035000,'San Isidro','district','straightforward','San Isidro is the primary financial district.','Ride to San Isidro and confirm the public approach.','Use the direct safe route to San Isidro and keep moving.','Check the nearest safe corner at San Isidro and continue.',20,true),
  ((select id from pack_refs where slug = 'lima'),'lima-barranco','Barranco',-12.148000,-77.022000,'Barranco','district','straightforward','Barranco is the historic bohemian district.','Ride to Barranco and confirm the public approach.','Use the direct safe route to Barranco and keep moving.','Check the nearest safe corner at Barranco and continue.',30,true),
  ((select id from pack_refs where slug = 'lima'),'lima-cercado-de-lima','Cercado de Lima',-12.046000,-77.042000,'Lima','district','straightforward','Cercado de Lima is the historic city center.','Ride to Cercado de Lima and confirm the public approach.','Use the direct safe route to Cercado de Lima and keep moving.','Check the nearest safe corner at Cercado de Lima and continue.',40,true),
  ((select id from pack_refs where slug = 'lima'),'lima-san-borja','San Borja',-12.107000,-76.999000,'San Borja','district','straightforward','San Borja is a major residential district.','Ride to San Borja and confirm the public approach.','Use the direct safe route to San Borja and keep moving.','Check the nearest safe corner at San Borja and continue.',50,true),
  ((select id from pack_refs where slug = 'lima'),'lima-la-molina','La Molina',-12.083000,-76.923000,'La Molina','district','straightforward','La Molina is an upscale residential district hub.','Ride to La Molina and confirm the public approach.','Use the direct safe route to La Molina and keep moving.','Check the nearest safe corner at La Molina and continue.',60,true),
  ((select id from pack_refs where slug = 'lima'),'lima-chosica','Chosica',-11.943100,-76.709400,'Lurigancho','town','straightforward','Chosica is an eastern satellite town in the Rimac valley.','Ride to Chosica and confirm the public approach.','Use the direct safe route to Chosica and keep moving.','Check the nearest safe corner at Chosica and continue.',70,true),
  ((select id from pack_refs where slug = 'lima'),'lima-chaclacayo','Chaclacayo',-11.994800,-76.768300,'Chaclacayo','district','straightforward','Chaclacayo is an eastern valley satellite.','Ride to Chaclacayo and confirm the public approach.','Use the direct safe route to Chaclacayo and keep moving.','Check the nearest safe corner at Chaclacayo and continue.',80,true),
  ((select id from pack_refs where slug = 'lima'),'lima-cieneguilla','Cieneguilla',-12.110000,-76.815000,'Cieneguilla','district','straightforward','Cieneguilla is a rural eastern satellite district.','Ride to Cieneguilla and confirm the public approach.','Use the direct safe route to Cieneguilla and keep moving.','Check the nearest safe corner at Cieneguilla and continue.',90,true),
  ((select id from pack_refs where slug = 'lima'),'lima-pachacamac','Pachacamac',-12.209500,-76.853900,'Pachacamac','district','straightforward','Pachacamac is a historic southern satellite district.','Ride to Pachacamac and confirm the public approach.','Use the direct safe route to Pachacamac and keep moving.','Check the nearest safe corner at Pachacamac and continue.',100,true),
  ((select id from pack_refs where slug = 'lima'),'lima-lurin','Lurín',-12.272000,-76.864000,'Lurín','district','straightforward','Lurín is a southern coastal satellite district.','Ride to Lurín and confirm the public approach.','Use the direct safe route to Lurín and keep moving.','Check the nearest safe corner at Lurín and continue.',110,true),
  ((select id from pack_refs where slug = 'lima'),'lima-punta-hermosa','Punta Hermosa',-12.310800,-76.813900,'Punta Hermosa','district','straightforward','Punta Hermosa is a major southern beach satellite.','Ride to Punta Hermosa and confirm the public approach.','Use the direct safe route to Punta Hermosa and keep moving.','Check the nearest safe corner at Punta Hermosa and continue.',120,true),
  ((select id from pack_refs where slug = 'lima'),'lima-punta-negra','Punta Negra',-12.360100,-76.796300,'Punta Negra','district','straightforward','Punta Negra is a southern coastal town satellite.','Ride to Punta Negra and confirm the public approach.','Use the direct safe route to Punta Negra and keep moving.','Check the nearest safe corner at Punta Negra and continue.',130,true),
  ((select id from pack_refs where slug = 'lima'),'lima-san-bartolo','San Bartolo',-12.385000,-76.770500,'San Bartolo','district','straightforward','San Bartolo is a classic southern satellite town.','Ride to San Bartolo and confirm the public approach.','Use the direct safe route to San Bartolo and keep moving.','Check the nearest safe corner at San Bartolo and continue.',140,true),
  ((select id from pack_refs where slug = 'lima'),'lima-santa-maria','Santa Maria del Mar',-12.405900,-76.774300,'Santa Maria del Mar','district','straightforward','Santa Maria is a southern coastal satellite.','Ride to Santa Maria del Mar and confirm the public approach.','Use the direct safe route to Santa Maria del Mar and keep moving.','Check the nearest safe corner at Santa Maria del Mar and continue.',150,true),
  ((select id from pack_refs where slug = 'lima'),'lima-pucusana','Pucusana',-12.475600,-76.792000,'Pucusana','district','straightforward','Pucusana is the southernmost provincial satellite.','Ride to Pucusana and confirm the public approach.','Use the direct safe route to Pucusana and keep moving.','Check the nearest safe corner at Pucusana and continue.',160,true),
  ((select id from pack_refs where slug = 'lima'),'lima-ancon','Ancón',-11.710000,-77.125500,'Ancón','district','straightforward','Ancón is a northern coastal satellite district.','Ride to Ancón and confirm the public approach.','Use the direct safe route to Ancón and keep moving.','Check the nearest safe corner at Ancón and continue.',170,true),
  ((select id from pack_refs where slug = 'lima'),'lima-santa-rosa','Santa Rosa',-11.806700,-77.165800,'Santa Rosa','district','straightforward','Santa Rosa is a northern coastal satellite town.','Ride to Santa Rosa and confirm the public approach.','Use the direct safe route to Santa Rosa and keep moving.','Check the nearest safe corner at Santa Rosa and continue.',180,true),
  ((select id from pack_refs where slug = 'lima'),'lima-comas','Comas',-11.934000,-77.042000,'Comas','district','straightforward','Comas is a major metropolitan hub in the north.','Ride to Comas and confirm the public approach.','Use the direct safe route to Comas and keep moving.','Check the nearest safe corner at Comas and continue.',190,true),
  ((select id from pack_refs where slug = 'lima'),'lima-ves','Villa El Salvador',-12.215000,-76.935000,'Villa El Salvador','district','straightforward','Villa El Salvador is a major southern metropolitan hub.','Ride to Villa El Salvador and confirm the public approach.','Use the direct safe route to Villa El Salvador and keep moving.','Check the nearest safe corner at Villa El Salvador and continue.',200,true)
on conflict (slug) do update
set
  pack_id = excluded.pack_id,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  district = excluded.district,
  category = excluded.category,
  vibe = excluded.vibe,
  hint = excluded.hint,
  task_local = excluded.task_local,
  task_fast = excluded.task_fast,
  task_chaotic = excluded.task_chaotic,
  sort_weight = excluded.sort_weight,
  is_active = excluded.is_active,
  updated_at = now();
