-- Tier 4 city batch seed: Hong Kong, Manila, Jakarta (Expanded to 20 checkpoints per city)
-- Additive and re-runnable. Apply manually in Supabase SQL Editor.
-- Fix: Included mandatory task strings to satisfy NOT NULL constraints.

insert into public.city_packs (slug, name, route_note, finish_label, safety_note, is_active)
values
  ('hongkong', 'Hong Kong', 'Island districts, Kowloon corridors, and New Territories metro towns around Hong Kong.', 'Hong Kong Tier 4 sheet complete.', 'Ride inside local laws, stay alert in narrow central streets, and keep every checkpoint public.', true),
  ('manila', 'Manila', 'Historic districts, business hubs, and metropolitan areas across the Manila region.', 'Manila Tier 4 sheet complete.', 'Ride inside local laws, stay predictable in heavy traffic, and use safe public routes.', true),
  ('jakarta', 'Jakarta', 'Central neighborhoods, business corridors, and metropolitan municipalities around Jakarta.', 'Jakarta Tier 4 sheet complete.', 'Ride inside local laws, stay alert in dense urban traffic, and keep checkpoints public.', true)
on conflict (slug) do update
set
  name = excluded.name,
  route_note = excluded.route_note,
  finish_label = excluded.finish_label,
  safety_note = excluded.safety_note,
  is_active = excluded.is_active,
  updated_at = now();

with pack_refs as (
  select id, slug from public.city_packs where slug in ('hongkong', 'manila', 'jakarta')
)
insert into public.city_checkpoints (
  pack_id,
  slug,
  name,
  lat,
  lng,
  district,
  category,
  vibe,
  hint,
  task_local,
  task_fast,
  task_chaotic,
  sort_weight,
  is_active
)
values
  -- Hong Kong
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-central','Central',22.282000,114.158000,'Central and Western','district','straightforward','Central is the business heart of Hong Kong Island.','Ride to Central and confirm the public approach.','Use the direct safe route to Central and keep moving.','Check the nearest safe corner at Central and continue.',10,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-wan-chai','Wan Chai',22.276000,114.172000,'Wan Chai','district','straightforward','Wan Chai is a vibrant commercial district on the island.','Ride to Wan Chai and confirm the public approach.','Use the direct safe route to Wan Chai and keep moving.','Check the nearest safe corner at Wan Chai and continue.',20,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-tsim-sha-tsui','Tsim Sha Tsui',22.298000,114.172000,'Yau Tsim Mong','district','straightforward','Tsim Sha Tsui is the southern tip of Kowloon.','Ride to Tsim Sha Tsui and confirm the public approach.','Use the direct safe route to Tsim Sha Tsui and keep moving.','Check the nearest safe corner at Tsim Sha Tsui and continue.',30,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-mong-kok','Mong Kok',22.319000,114.169000,'Yau Tsim Mong','district','straightforward','Mong Kok is a dense urban district in Kowloon.','Ride to Mong Kok and confirm the public approach.','Use the direct safe route to Mong Kok and keep moving.','Check the nearest safe corner at Mong Kok and continue.',40,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-causeway-bay','Causeway Bay',22.280000,114.185000,'Wan Chai','district','straightforward','Causeway Bay is a major shopping district.','Ride to Causeway Bay and confirm the public approach.','Use the direct safe route to Causeway Bay and keep moving.','Check the nearest safe corner at Causeway Bay and continue.',50,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-sha-tin','Sha Tin',22.376000,114.184000,'Sha Tin','district','straightforward','Sha Tin is a major town in the New Territories.','Ride to Sha Tin and confirm the public approach.','Use the direct safe route to Sha Tin and keep moving.','Check the nearest safe corner at Sha Tin and continue.',60,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-tuen-mun','Tuen Mun',22.391600,113.977200,'Tuen Mun','town','straightforward','Tuen Mun is a major satellite town in the western New Territories.','Ride to Tuen Mun and confirm the public approach.','Use the direct safe route to Tuen Mun and keep moving.','Check the nearest safe corner at Tuen Mun and continue.',70,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-yuen-long','Yuen Long',22.445500,114.022200,'Yuen Long','town','straightforward','Yuen Long is a vibrant commercial hub in the northwest.','Ride to Yuen Long and confirm the public approach.','Use the direct safe route to Yuen Long and keep moving.','Check the nearest safe corner at Yuen Long and continue.',80,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-fanling','Fanling',22.492200,114.138600,'North','town','straightforward','Fanling is a northern town near the border.','Ride to Fanling and confirm the public approach.','Use the direct safe route to Fanling and keep moving.','Check the nearest safe corner at Fanling and continue.',90,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-tai-po','Tai Po',22.450800,114.164100,'Tai Po','town','straightforward','Tai Po is a historic market town in the northeast.','Ride to Tai Po and confirm the public approach.','Use the direct safe route to Tai Po and keep moving.','Check the nearest safe corner at Tai Po and continue.',100,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-sai-kung','Sai Kung',22.381300,114.270500,'Sai Kung','town','straightforward','Sai Kung is the gateway to eastern islands and parks.','Ride to Sai Kung and confirm the public approach.','Use the direct safe route to Sai Kung and keep moving.','Check the nearest safe corner at Sai Kung and continue.',110,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-tung-chung','Tung Chung',22.286900,113.943600,'Islands','town','straightforward','Tung Chung is the gateway to Lantau and the airport.','Ride to Tung Chung and confirm the public approach.','Use the direct safe route to Tung Chung and keep moving.','Check the nearest safe corner at Tung Chung and continue.',120,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-lantau','Lantau',22.250000,113.916000,'Islands','island','straightforward','Lantau is the largest outlying island.','Ride to Lantau and confirm the public approach.','Use the direct safe route to Lantau and keep moving.','Check the nearest safe corner at Lantau and continue.',130,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-cheung-chau','Cheung Chau',22.210500,114.028800,'Islands','island','straightforward','Cheung Chau is a historic outlying island hub.','Ride to Cheung Chau and confirm the public approach.','Use the direct safe route to Cheung Chau and keep moving.','Check the nearest safe corner at Cheung Chau and continue.',140,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-lamma','Lamma Island',22.200000,114.116600,'Islands','island','straightforward','Lamma Island is a quiet car-free residential satellite.','Ride to Lamma Island and confirm the public approach.','Use the direct safe route to Lamma Island and keep moving.','Check the nearest safe corner at Lamma Island and continue.',150,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-peng-chau','Peng Chau',22.285200,114.038600,'Islands','island','straightforward','Peng Chau is a serene satellite island.','Ride to Peng Chau and confirm the public approach.','Use the direct safe route to Peng Chau and keep moving.','Check the nearest safe corner at Peng Chau and continue.',160,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-north-point','North Point',22.291000,114.197000,'Eastern','district','straightforward','North Point is a major residential and commercial hub.','Ride to North Point and confirm the public approach.','Use the direct safe route to North Point and keep moving.','Check the nearest safe corner at North Point and continue.',170,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-kwun-tong','Kwun Tong',22.313000,114.225000,'Kwun Tong','district','straightforward','Kwun Tong is a major commercial hub in Kowloon.','Ride to Kwun Tong and confirm the public approach.','Use the direct safe route to Kwun Tong and keep moving.','Check the nearest safe corner at Kwun Tong and continue.',180,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-tko','Tseung Kwan O',22.310000,114.260000,'Sai Kung','town','straightforward','TKO is a major modern satellite town.','Ride to Tseung Kwan O and confirm the public approach.','Use the direct safe route to Tseung Kwan O and keep moving.','Check the nearest safe corner at Tseung Kwan O and continue.',190,true),
  ((select id from pack_refs where slug = 'hongkong'),'hongkong-discovery-bay','Discovery Bay',22.295000,114.015000,'Islands','town','straightforward','Discovery Bay is a resort community satellite.','Ride to Discovery Bay and confirm the public approach.','Use the direct safe route to Discovery Bay and keep moving.','Check the nearest safe corner at Discovery Bay and continue.',200,true),

  -- Manila
  ((select id from pack_refs where slug = 'manila'),'manila-intramuros','Intramuros',14.591000,120.975000,'Manila','district','straightforward','Intramuros is the historic walled city center.','Ride to Intramuros and confirm the public approach.','Use the direct safe route to Intramuros and keep moving.','Check the nearest safe corner at Intramuros and continue.',10,true),
  ((select id from pack_refs where slug = 'manila'),'manila-binondo','Binondo',14.601000,120.975000,'Manila','district','straightforward','Binondo is the historic Chinatown hub.','Ride to Binondo and confirm the public approach.','Use the direct safe route to Binondo and keep moving.','Check the nearest safe corner at Binondo and continue.',20,true),
  ((select id from pack_refs where slug = 'manila'),'manila-ermita','Ermita',14.582000,120.980000,'Manila','district','straightforward','Ermita is a central administrative hub.','Ride to Ermita and confirm the public approach.','Use the direct safe route to Ermita and keep moving.','Check the nearest safe corner at Ermita and continue.',30,true),
  ((select id from pack_refs where slug = 'manila'),'manila-malate','Malate',14.568000,120.990000,'Manila','district','straightforward','Malate is a historic cultural district hub.','Ride to Malate and confirm the public approach.','Use the direct safe route to Malate and keep moving.','Check the nearest safe corner at Malate and continue.',40,true),
  ((select id from pack_refs where slug = 'manila'),'manila-makati','Makati',14.555000,121.022000,'Makati','municipality','straightforward','Makati is the primary financial hub.','Ride to Makati and confirm the public approach.','Use the direct safe route to Makati and keep moving.','Check the nearest safe corner at Makati and continue.',50,true),
  ((select id from pack_refs where slug = 'manila'),'manila-quezon-city','Quezon City',14.676000,121.043000,'Quezon City','municipality','straightforward','Quezon City is a major metropolitan hub.','Ride to Quezon City and confirm the public approach.','Use the direct safe route to Quezon City and keep moving.','Check the nearest safe corner at Quezon City and continue.',60,true),
  ((select id from pack_refs where slug = 'manila'),'manila-antipolo','Antipolo',14.584200,121.176300,'Rizal','municipality','straightforward','Antipolo is a major eastern satellite city.','Ride to Antipolo and confirm the public approach.','Use the direct safe route to Antipolo and keep moving.','Check the nearest safe corner at Antipolo and continue.',70,true),
  ((select id from pack_refs where slug = 'manila'),'manila-cainta','Cainta',14.578600,121.122200,'Rizal','municipality','straightforward','Cainta is a major metropolitan satellite hub.','Ride to Cainta and confirm the public approach.','Use the direct safe route to Cainta and keep moving.','Check the nearest safe corner at Cainta and continue.',80,true),
  ((select id from pack_refs where slug = 'manila'),'manila-taytay','Taytay',14.558800,121.132900,'Rizal','municipality','straightforward','Taytay is an eastern metropolitan satellite.','Ride to Taytay and confirm the public approach.','Use the direct safe route to Taytay and keep moving.','Check the nearest safe corner at Taytay and continue.',90,true),
  ((select id from pack_refs where slug = 'manila'),'manila-bacoor','Bacoor',14.459000,120.938500,'Cavite','municipality','straightforward','Bacoor is a major southern gateway satellite.','Ride to Bacoor and confirm the public approach.','Use the direct safe route to Bacoor and keep moving.','Check the nearest safe corner at Bacoor and continue.',100,true),
  ((select id from pack_refs where slug = 'manila'),'manila-imus','Imus',14.429700,120.936700,'Cavite','municipality','straightforward','Imus is a major commercial satellite hub.','Ride to Imus and confirm the public approach.','Use the direct safe route to Imus and keep moving.','Check the nearest safe corner at Imus and continue.',110,true),
  ((select id from pack_refs where slug = 'manila'),'manila-dasmarinas','Dasmariñas',14.329400,120.936700,'Cavite','municipality','straightforward','Dasmariñas is a major southern industrial satellite.','Ride to Dasmariñas and confirm the public approach.','Use the direct safe route to Dasmariñas and keep moving.','Check the nearest safe corner at Dasmariñas and continue.',120,true),
  ((select id from pack_refs where slug = 'manila'),'manila-san-pedro','San Pedro',14.359500,121.047300,'Laguna','municipality','straightforward','San Pedro is a southern provincial satellite hub.','Ride to San Pedro and confirm the public approach.','Use the direct safe route to San Pedro and keep moving.','Check the nearest safe corner at San Pedro and continue.',130,true),
  ((select id from pack_refs where slug = 'manila'),'manila-binan','Biñan',14.342700,121.080700,'Laguna','municipality','straightforward','Biñan is a major industrial satellite hub.','Ride to Biñan and confirm the public approach.','Use the direct safe route to Biñan and keep moving.','Check the nearest safe corner at Biñan and continue.',140,true),
  ((select id from pack_refs where slug = 'manila'),'manila-meycauayan','Meycauayan',14.736900,120.960800,'Bulacan','municipality','straightforward','Meycauayan is a northern provincial satellite.','Ride to Meycauayan and confirm the public approach.','Use the direct safe route to Meycauayan and keep moving.','Check the nearest safe corner at Meycauayan and continue.',150,true),
  ((select id from pack_refs where slug = 'manila'),'manila-sjdm','San Jose del Monte',14.813900,121.045300,'Bulacan','municipality','straightforward','SJDM is a major northern satellite hub.','Ride to San Jose del Monte and confirm the public approach.','Use the direct safe route to San Jose del Monte and keep moving.','Check the nearest safe corner at San Jose del Monte and continue.',160,true),
  ((select id from pack_refs where slug = 'manila'),'manila-taguig','Taguig (BGC)',14.549000,121.045000,'Taguig','district','straightforward','BGC is a major modern metropolitan hub.','Ride to Taguig (BGC) and confirm the public approach.','Use the direct safe route to Taguig (BGC) and keep moving.','Check the nearest safe corner at Taguig (BGC) and continue.',170,true),
  ((select id from pack_refs where slug = 'manila'),'manila-pasay','Pasay',14.537000,121.001000,'Pasay','municipality','straightforward','Pasay is a major metropolitan commercial hub.','Ride to Pasay and confirm the public approach.','Use the direct safe route to Pasay and keep moving.','Check the nearest safe corner at Pasay and continue.',180,true),
  ((select id from pack_refs where slug = 'manila'),'manila-caloocan','Caloocan',14.641000,120.973000,'Caloocan','municipality','straightforward','Caloocan is a major metropolitan hub in the north.','Ride to Caloocan and confirm the public approach.','Use the direct safe route to Caloocan and keep moving.','Check the nearest safe corner at Caloocan and continue.',190,true),
  ((select id from pack_refs where slug = 'manila'),'manila-las-pinas','Las Piñas',14.444000,120.993000,'Las Piñas','municipality','straightforward','Las Piñas is a southern metropolitan satellite hub.','Ride to Las Piñas and confirm the public approach.','Use the direct safe route to Las Piñas and keep moving.','Check the nearest safe corner at Las Piñas and continue.',200,true),

  -- Jakarta
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-menteng','Menteng',-6.191000,106.833000,'Jakarta Pusat','district','straightforward','Menteng is a central residential hub.','Ride to Menteng and confirm the public approach.','Use the direct safe route to Menteng and keep moving.','Check the nearest safe corner at Menteng and continue.',10,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-sudirman','Sudirman',-6.215000,106.816000,'Jakarta Pusat','district','straightforward','Sudirman is the primary business hub.','Ride to Sudirman and confirm the public approach.','Use the direct safe route to Sudirman and keep moving.','Check the nearest safe corner at Sudirman and continue.',20,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-kemang','Kemang',-6.273000,106.815000,'Jakarta Selatan','district','straightforward','Kemang is a major cultural and residential hub.','Ride to Kemang and confirm the public approach.','Use the direct safe route to Kemang and keep moving.','Check the nearest safe corner at Kemang and continue.',30,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-glodok','Glodok',-6.143000,106.812000,'Jakarta Barat','district','straightforward','Glodok is the historic center hub.','Ride to Glodok and confirm the public approach.','Use the direct safe route to Glodok and keep moving.','Check the nearest safe corner at Glodok and continue.',40,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-kelapa-gading','Kelapa Gading',-6.155000,106.902000,'Jakarta Utara','district','straightforward','Kelapa Gading is a major northern commercial hub.','Ride to Kelapa Gading and confirm the public approach.','Use the direct safe route to Kelapa Gading and keep moving.','Check the nearest safe corner at Kelapa Gading and continue.',50,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-senayan','Senayan',-6.225000,106.802000,'Jakarta Pusat','district','straightforward','Senayan is a major sports and business hub.','Ride to Senayan and confirm the public approach.','Use the direct safe route to Senayan and keep moving.','Check the nearest safe corner at Senayan and continue.',60,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-bogor','Bogor',-6.594400,106.789200,'Bogor','municipality','straightforward','Bogor is a major southern satellite city.','Ride to Bogor and confirm the public approach.','Use the direct safe route to Bogor and keep moving.','Check the nearest safe corner at Bogor and continue.',70,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-depok','Depok',-6.402900,106.778400,'Depok','municipality','straightforward','Depok is a major metropolitan satellite hub.','Ride to Depok and confirm the public approach.','Use the direct safe route to Depok and keep moving.','Check the nearest safe corner at Depok and continue.',80,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-tangerang','Tangerang',-6.178300,106.631900,'Tangerang','municipality','straightforward','Tangerang is a major western satellite city.','Ride to Tangerang and confirm the public approach.','Use the direct safe route to Tangerang and keep moving.','Check the nearest safe corner at Tangerang and continue.',90,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-bekasi','Bekasi',-6.234900,106.989600,'Bekasi','municipality','straightforward','Bekasi is a major eastern metropolitan satellite hub.','Ride to Bekasi and confirm the public approach.','Use the direct safe route to Bekasi and keep moving.','Check the nearest safe corner at Bekasi and continue.',100,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-south-tangerang','South Tangerang',-6.288600,106.717900,'Banten','municipality','straightforward','South Tangerang is a major southwestern satellite hub.','Ride to South Tangerang and confirm the public approach.','Use the direct safe route to South Tangerang and keep moving.','Check the nearest safe corner at South Tangerang and continue.',110,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-sentul','Sentul',-6.534800,106.854100,'Bogor','town','straightforward','Sentul is a planned satellite city hub.','Ride to Sentul and confirm the public approach.','Use the direct safe route to Sentul and keep moving.','Check the nearest safe corner at Sentul and continue.',120,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-cikarang','Cikarang',-6.261100,107.152800,'Bekasi','town','straightforward','Cikarang is a major industrial satellite hub.','Ride to Cikarang and confirm the public approach.','Use the direct safe route to Cikarang and keep moving.','Check the nearest safe corner at Cikarang and continue.',130,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-cibubur','Cibubur',-6.372600,106.868500,'Jakarta Timur','district','straightforward','Cibubur is a major metropolitan satellite hub.','Ride to Cibubur and confirm the public approach.','Use the direct safe route to Cibubur and keep moving.','Check the nearest safe corner at Cibubur and continue.',140,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-bsd','BSD City',-6.282100,106.668100,'Tangerang','town','straightforward','BSD City is a major planned satellite hub.','Ride to BSD City and confirm the public approach.','Use the direct safe route to BSD City and keep moving.','Check the nearest safe corner at BSD City and continue.',150,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-karawaci','Karawaci',-6.203800,106.630200,'Tangerang','town','straightforward','Karawaci is a major commercial satellite hub.','Ride to Karawaci and confirm the public approach.','Use the direct safe route to Karawaci and keep moving.','Check the nearest safe corner at Karawaci and continue.',160,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-pluit','Pluit',-6.115000,106.785000,'Jakarta Utara','district','straightforward','Pluit is a major coastal residential hub.','Ride to Pluit and confirm the public approach.','Use the direct safe route to Pluit and keep moving.','Check the nearest safe corner at Pluit and continue.',170,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-pik','Pantai Indah Kapuk',-6.110000,106.745000,'Jakarta Utara','district','straightforward','PIK is a modern coastal satellite hub.','Ride to Pantai Indah Kapuk and confirm the public approach.','Use the direct safe route to Pantai Indah Kapuk and keep moving.','Check the nearest safe corner at Pantai Indah Kapuk and continue.',180,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-kuningan','Kuningan',-6.220000,106.825000,'Jakarta Selatan','district','straightforward','Kuningan is a major central business hub.','Ride to Kuningan and confirm the public approach.','Use the direct safe route to Kuningan and keep moving.','Check the nearest safe corner at Kuningan and continue.',190,true),
  ((select id from pack_refs where slug = 'jakarta'),'jakarta-pondok-indah','Pondok Indah',-6.265000,106.785000,'Jakarta Selatan','district','straightforward','Pondok Indah is an upscale residential hub.','Ride to Pondok Indah and confirm the public approach.','Use the direct safe route to Pondok Indah and keep moving.','Check the nearest safe corner at Pondok Indah and continue.',200,true)
on conflict (slug) do update
set
  pack_id = excluded.pack_id,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  district = excluded.district,
  category = excluded.category,
  vibe = excluded.vibe,
  hint = excluded.hint,
  task_local = excluded.task_local,
  task_fast = excluded.task_fast,
  task_chaotic = excluded.task_chaotic,
  sort_weight = excluded.sort_weight,
  is_active = excluded.is_active,
  updated_at = now();
