-- City batch seed: Chicago, Los Angeles, Philadelphia, Seattle, Buenos Aires, Krakow

insert into public.city_packs (slug, name, route_note, finish_label, safety_note, is_active)
values
  ('chicago', 'Chicago', 'Grid pressure, river drag, and long blocks that punish soft timing.', 'Sheet clear, lake wind still talking, line held.', 'Ride inside local laws, stay sharp in traffic, and keep every task grounded in the real street.', true),
  ('losangeles', 'Los Angeles', 'Long lights, bridge pull, and block cuts that only feel smart after you commit.', 'List clear, city wide open, no soft excuses left.', 'Ride inside local laws, stay sharp in traffic, and keep every task realistic on live streets.', true),
  ('philadelphia', 'Philadelphia', 'Grid cuts, bridge reads, and enough rough edges to punish lazy calls.', 'Close the sheet, hold the pace, let the city talk back.', 'Ride inside local laws, stay aware in traffic, and keep every task safe and doable.', true),
  ('seattle', 'Seattle', 'Hill run-ups, water drag, and side-street reads that only make sense once you trust them.', 'Sheet clear, lungs hot, line still clean.', 'Ride inside local laws, stay sharp on climbs and descents, and keep every task grounded.', true),
  ('buenosaires', 'Buenos Aires', 'Old-core cuts, dock drag, and enough block rhythm to punish weak reads.', 'List clear, pace held, city still staring.', 'Ride inside local laws, stay predictable in traffic, and keep every task realistic.', true),
  ('krakow', 'Krakow', 'Old-town seams, river pull, and tram edges that punish soft timing.', 'Sheet clear, line neat, city still judging.', 'Ride inside local laws, stay sharp around trams and traffic, and keep every task safe.', true)
on conflict (slug) do update
set
  name = excluded.name,
  route_note = excluded.route_note,
  finish_label = excluded.finish_label,
  safety_note = excluded.safety_note,
  is_active = excluded.is_active,
  updated_at = now();

with pack_refs as (
  select id, slug from public.city_packs where slug in ('chicago', 'losangeles', 'philadelphia', 'seattle', 'buenosaires', 'krakow')
)
insert into public.city_checkpoints (
  pack_id,
  slug,
  name,
  lat,
  lng,
  district,
  category,
  vibe,
  hint,
  task_local,
  task_fast,
  task_chaotic,
  sort_weight,
  is_active
)
values
  ((select id from pack_refs where slug = 'chicago'),'chicago-loop-seam','Loop Seam',41.8821,-87.6315,'The Loop','seam','signal-pressure','Signal pressure, canyon wind, and no reward for soft timing.','Clock the side street riders actually trust in the middle of the rush.','Touch the seam and lock the hard exit instantly.','Give the canyon one fake dispatch line and disappear.',10,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-riverwalk-cut','Riverwalk Cut',41.8880,-87.6288,'River North','waterline','water-pull','Water pull nearby, cleaner blocks if you leave it on time.','Clock the exact point the river stops helping and starts baiting you.','Touch the cut and get back into the grid before it softens the move.','Throw one fake title-defense nod at the water and bounce.',20,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-west-loop-line','West Loop Line',41.8843,-87.6471,'West Loop','line','warehouse-rhythm','Long blocks, warehouse rhythm, and no patience for bad reads.','Clock the lane that feels more rider than office spill.','Touch the line and keep the cadence blunt.','Give the strip one fake sponsor shout and move on.',30,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-pilsen-cut','Pilsen Cut',41.8578,-87.6655,'Pilsen','street-cut','wall-run','Wall runs, worker corners, and cleaner exits than they want to admit.','Clock the least polished useful corner and trust it.','Touch the cut and keep the pace sharp.','Rate the block like a harsh race judge and get gone.',40,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-wicker-pocket','Wicker Pocket',41.9083,-87.6779,'Wicker Park','pocket','short-reset','Short pocket, fast exits, no help if you get soft.','Clock how fast the block mood changes when you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and move on.',50,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-logan-runup','Logan Run-Up',41.9297,-87.7081,'Logan Square','run-up','square-pressure','Square pressure and one clean spoke if you take it early.','Clock the line locals still trust when the circle gets weird.','Touch the run-up and commit before hesitation costs speed.','Give the square one sarcastic compliment and keep rolling.',60,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-bridgeport-line','Bridgeport Line',41.8376,-87.6526,'Bridgeport','line','worker-block','Worker blocks and no reward for scenic pacing.','Clock the block that feels most like regulars still own it.','Touch the line and trust the cleaner side instantly.','Make one fake race-radio call and disappear.',70,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-hyde-park-edge','Hyde Park Edge',41.7943,-87.5907,'Hyde Park','water-edge','lake-drag','Lake drag, long reads, and no help if you start admiring it.','Clock the least postcard angle and trust it more than the obvious one.','Touch the edge and get back into the city before the lake softens you.','Throw one fake champion glare at the water and cut out.',80,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-south-loop-cut','South Loop Cut',41.8677,-87.6244,'South Loop','street-cut','rail-pressure','Fast blocks, rail pressure, and no room for soft reads.','Clock the lane riders actually trust when the block gets loud.','Touch the cut and keep the cadence sharp.','Give the block one fake dispatch line and vanish.',90,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-streeterville-line','Streeterville Line',41.8924,-87.6211,'Streeterville','line','center-lake-pull','Lake pull nearby, center pressure, and cleaner seams than they look.','Clock the least postcard corner and trust it over the obvious one.','Touch the line and get out before the water softens you.','Throw one fake title-defense nod at the lake and move on.',100,true),
  ((select id from pack_refs where slug = 'chicago'),'chicago-fulton-pocket','Fulton Pocket',41.8868,-87.6485,'West Loop','pocket','short-reset','Short pocket, fast exits, and no reward for drifting.','Clock how fast the district mood changes when you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and bounce.',110,true),

  ((select id from pack_refs where slug = 'losangeles'),'la-dtla-seam','DTLA Seam',34.0488,-118.2518,'Downtown','seam','tower-pressure','Tower pressure, long lights, and no reward for soft timing.','Clock the block that feels more messenger than office spill.','Touch the seam and keep the pace blunt.','Give the canyon one fake dispatch line and vanish.',10,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-arts-district-cut','Arts District Cut',34.0404,-118.2359,'Arts District','street-cut','warehouse-drag','Warehouse drag and cleaner seams just off the obvious line.','Clock the least polished useful corner and trust it.','Touch the cut and trust the hard exit instantly.','Give the block one fake sponsor tag and move on.',20,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-chinatown-line','Chinatown Line',34.0654,-118.2380,'Chinatown','line','tight-rhythm','Tight block rhythm and no patience for bad reads.','Clock the lane riders actually trust when the block gets loud.','Touch the line and keep the cadence sharp.','Make one fake race-radio call and disappear.',30,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-echo-park-pocket','Echo Park Pocket',34.0781,-118.2606,'Echo Park','pocket','hill-bite','Short pocket, hill bite, and no help if you get soft.','Clock how fast the mood changes once you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and bounce.',40,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-koreatown-cut','Koreatown Cut',34.0629,-118.3082,'Koreatown','street-cut','dense-read','Dense blocks, long reads, and no reward for drifting.','Clock the side street that feels cleaner than the boulevard deserves.','Touch the cut and lock the clean seam in one glance.','Give the avenue one sarcastic compliment and get gone.',50,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-westlake-line','Westlake Line',34.0585,-118.2762,'Westlake','line','bus-pressure','Fast city line, bus pressure, and no room for soft timing.','Clock the cross street riders would actually trust here.','Touch the line and keep the move blunt.','Give the strip one fake title-defense nod and move on.',60,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-boyle-heights-runup','Boyle Heights Run-Up',34.0370,-118.2105,'Boyle Heights','run-up','bridge-pull','Bridge pull, fast roads, and awkward approach choices.','Clock the exact point the bridge starts owning the block.','Touch the run-up and commit before hesitation costs speed.','Throw one fake champion stare at the bridge and keep rolling.',70,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-silver-lake-edge','Silver Lake Edge',34.0899,-118.2702,'Silver Lake','edge','hill-water','Hill edge, reservoir drag nearby, and no need for scenic pacing.','Clock the least polished corner and trust it over the clean one.','Touch the edge and get back into the city before it softens you.','Give the hill one fake podium nod and cut out.',80,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-little-tokyo-line','Little Tokyo Line',34.0496,-118.2395,'Little Tokyo','line','tight-center-rhythm','Tight center rhythm and no patience for bad timing.','Clock the side lane riders would actually trust here.','Touch the line and keep the move blunt.','Give the block one fake dispatch line and get gone.',90,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-historic-core-cut','Historic Core Cut',34.0468,-118.2510,'Downtown','street-cut','old-core-pressure','Old-core cut, long lights, and no reward for soft reads.','Clock the least polished useful corner and trust it.','Touch the cut and trust the hard exit instantly.','Make one fake race-radio call and disappear.',100,true),
  ((select id from pack_refs where slug = 'losangeles'),'la-south-park-pocket','South Park Pocket',34.0430,-118.2666,'South Park','pocket','short-reset','Short pocket, fast exits, and one clean side if you read it early.','Clock how fast the district mood changes once you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and move on.',110,true),

  ((select id from pack_refs where slug = 'philadelphia'),'philly-center-city-seam','Center City Seam',39.9524,-75.1636,'Center City','seam','grid-pressure','Grid pressure, bus lanes, and no reward for hesitation.','Clock the side street riders actually trust in the middle of the rush.','Touch the seam and trust the hard exit instantly.','Give the block one fake dispatch line and vanish.',10,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-old-city-line','Old City Line',39.9496,-75.1456,'Old City','line','old-core','Old-core blocks, river pull nearby, and cleaner seams than they look.','Clock the least postcard corner and trust it over the obvious one.','Touch the line and keep the cadence sharp.','Give the whole strip one sarcastic compliment and move on.',20,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-fishtown-cut','Fishtown Cut',39.9690,-75.1355,'Fishtown','street-cut','fast-blocks','Fast blocks, rail drag, and no room for soft timing.','Clock the lane that feels more rider than weekend spill.','Touch the cut and keep the pace blunt.','Make one fake race-radio call and disappear.',30,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-nolibs-pocket','NoLibs Pocket',39.9665,-75.1404,'Northern Liberties','pocket','short-reset','Short pocket, fast exits, and one clean move if you read it early.','Clock how fast the block mood changes when you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and bounce.',40,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-fairmount-line','Fairmount Line',39.9650,-75.1733,'Fairmount','line','museum-pull','Museum pull nearby, cleaner blocks if you skip the obvious line.','Clock the corner that feels most like locals still own it.','Touch the line and trust the cleaner side instantly.','Give the avenue one fake title-defense nod and get gone.',50,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-university-seam','University Seam',39.9522,-75.1932,'University City','seam','bridge-pressure','Campus edge, bridge pressure, and no reward for drifting.','Clock the side lane that feels cleaner than the main road deserves.','Touch the seam and keep the move blunt.','Rate the block like a harsh race judge and disappear.',60,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-south-street-cut','South Street Cut',39.9431,-75.1642,'South Philly','street-cut','crowd-pressure','Crowd pressure and cleaner seams just off the main pull.','Clock the least polished useful corner and trust it.','Touch the cut and get out before the drag sets in.','Give the strip one fake sponsor shout and move on.',70,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-passyunk-run','Passyunk Run',39.9309,-75.1652,'East Passyunk','run-up','weird-angle','Fast line, weird angles, and no help if you get soft.','Clock the exact line riders would actually trust here.','Touch the run and commit before hesitation costs speed.','Throw one fake champion glare at the avenue and keep rolling.',80,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-market-east-line','Market East Line',39.9528,-75.1558,'Center City','line','transit-pressure','Transit pressure, center drag, and no room for soft timing.','Clock the side street riders actually trust here.','Touch the line and keep the cadence sharp.','Give the avenue one fake dispatch line and move on.',90,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-rittenhouse-cut','Rittenhouse Cut',39.9495,-75.1716,'Rittenhouse','street-cut','pretty-trap','Pretty trap, cleaner seams if you skip the soft pull.','Clock the least polished useful corner and trust it.','Touch the cut and leave before the block goes soft.','Rate the square like a harsh race judge and bounce.',100,true),
  ((select id from pack_refs where slug = 'philadelphia'),'philly-washington-square-pocket','Washington Square Pocket',39.9473,-75.1538,'Washington Square West','pocket','short-reset','Short pocket, fast exits, and no reward for drifting.','Clock how fast the mood changes when you hit the pocket.','Touch the pocket and get gone before it flattens you.','Act like this was your lane all week and keep rolling.',110,true),

  ((select id from pack_refs where slug = 'seattle'),'seattle-pioneer-seam','Pioneer Seam',47.6019,-122.3338,'Pioneer Square','seam','brick-pressure','Brick pressure, stadium drag, and cleaner exits than they want to admit.','Clock the lane that feels more messenger than game-day spill.','Touch the seam and trust the hard exit instantly.','Give the block one fake dispatch line and disappear.',10,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-belltown-line','Belltown Line',47.6143,-122.3474,'Belltown','line','water-pull','Fast grid, water pull nearby, and no reward for drifting.','Clock the side street riders actually trust when the block gets loud.','Touch the line and keep the cadence sharp.','Give the strip one fake title-defense nod and move on.',20,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-capitol-cut','Capitol Cut',47.6231,-122.3192,'Capitol Hill','street-cut','hill-bite','Hill bite, dense corners, and no room for soft timing.','Clock the least polished useful corner and trust it.','Touch the cut and keep the pace blunt.','Make one fake race-radio call and disappear.',30,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-slu-pocket','SLU Pocket',47.6226,-122.3370,'South Lake Union','pocket','machine-block','Machine blocks, short pocket, and one clean side if you read it early.','Clock how fast the district mood changes when you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and bounce.',40,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-cid-line','CID Line',47.5984,-122.3258,'International District','line','transit-pressure','Transit pressure, long reads, and no help if you drift.','Clock the line riders actually trust when the block gets crowded.','Touch the line and trust the cleaner side instantly.','Give the avenue one sarcastic compliment and get gone.',50,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-queen-anne-runup','Queen Anne Run-Up',47.6236,-122.3560,'Lower Queen Anne','run-up','hill-gravity','Hill run-up and awkward approach choices that punish hesitation.','Clock the exact point the climb starts owning the block.','Touch the run-up and commit before hesitation costs speed.','Throw one fake champion stare at the hill and keep rolling.',60,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-central-seam','Central Seam',47.6084,-122.3021,'Central District','seam','fast-city','Fast city seam and no patience for bad reads.','Clock the side lane that feels cleaner than the main road deserves.','Touch the seam and keep the move neat, not polite.','Rate the strip like a harsh race judge and move on.',70,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-fremont-edge','Fremont Edge',47.6504,-122.3502,'Fremont','water-edge','canal-drag','Canal edge, bridge drag, and no reason to coast.','Clock the least postcard angle and trust it over the obvious one.','Touch the edge and get back into the city before the water softens you.','Give the canal one fake sponsor shout and cut out.',80,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-waterfront-line','Waterfront Line',47.6054,-122.3417,'Waterfront','waterline','ferry-pull','Water drag, ferry pull, and cleaner exits if you leave it early.','Clock the exact point the water stops helping and starts baiting you.','Touch the line and get back into the grid before it softens the move.','Throw one fake title-defense nod at the bay and move on.',90,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-first-hill-cut','First Hill Cut',47.6094,-122.3239,'First Hill','street-cut','hill-bite','Hill bite, hospital blocks, and no reward for soft timing.','Clock the lane riders actually trust when the block gets weird.','Touch the cut and keep the pace blunt.','Make one fake dispatch call and disappear.',100,true),
  ((select id from pack_refs where slug = 'seattle'),'seattle-downtown-pocket','Downtown Pocket',47.6074,-122.3347,'Downtown','pocket','short-reset','Short pocket, fast exits, and one clean side if you read it early.','Clock how fast the district mood changes once you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and bounce.',110,true),

  ((select id from pack_refs where slug = 'buenosaires'),'ba-san-telmo-cut','San Telmo Cut',-34.6218,-58.3732,'San Telmo','street-cut','old-core-drag','Old-core drag and cleaner seams if you trust them early.','Clock the corner that feels more rider than cafe spill.','Touch the cut and keep the pace blunt.','Give the block one fake dispatch line and vanish.',10,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-microcentro-line','Microcentro Line',-34.6037,-58.3816,'Microcentro','line','center-pressure','Center pressure, bus lanes, and no reward for drifting.','Clock the side lane riders would actually trust here.','Touch the line and trust the hard exit instantly.','Give the avenue one sarcastic compliment and move on.',20,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-puerto-madero-seam','Puerto Madero Seam',-34.6118,-58.3639,'Puerto Madero','waterline','water-drag','Water drag and cleaner blocks if you leave the obvious line on time.','Clock the exact point the water stops helping and starts baiting you.','Touch the seam and get back into the grid before it softens the move.','Throw one fake title-defense nod at the water and bounce.',30,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-la-boca-run','La Boca Run',-34.6345,-58.3644,'La Boca','run-up','dock-edge','Dock edge, rough reads, and no room for soft timing.','Clock the block that feels more worker than postcard.','Touch the run and commit before hesitation costs speed.','Give the whole strip one fake sponsor shout and disappear.',40,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-barracas-pocket','Barracas Pocket',-34.6438,-58.3771,'Barracas','pocket','short-reset','Short pocket, rail drag, and one clean side if you read it early.','Clock how fast the district mood changes when you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and move on.',50,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-palermo-line','Palermo Line',-34.5864,-58.4233,'Palermo','line','long-city','Long city line and no patience for bad reads.','Clock the side street that feels cleaner than the avenue deserves.','Touch the line and keep the cadence sharp.','Make one fake race-radio call and get gone.',60,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-recoleta-cut','Recoleta Cut',-34.5889,-58.3929,'Recoleta','street-cut','pretty-trap','Pretty trap and better cuts hiding off the clean pull.','Find the least polished useful corner and trust it.','Touch the cut and leave before the block goes soft.','Rate the block like a harsh race judge and bounce.',70,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-almagro-edge','Almagro Edge',-34.6095,-58.4182,'Almagro','edge','grid-fast','Grid edge, fast reads, and no help if you get soft.','Clock the line locals still trust when the block gets loud.','Touch the edge and keep the move neat, not polite.','Give the avenue one fake title nod and cut out.',80,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-monserrat-line','Monserrat Line',-34.6112,-58.3795,'Monserrat','line','center-pressure','Center line, old-core pressure, and no patience for bad reads.','Clock the side lane riders would actually trust here.','Touch the line and keep the cadence sharp.','Give the block one fake dispatch line and get gone.',90,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-plaza-mayo-seam','Plaza Mayo Seam',-34.6081,-58.3702,'Monserrat','seam','open-center','Open center seam and one clean exit if you stay blunt.','Clock the least postcard corner and trust it over the obvious one.','Touch the seam and trust the hard exit instantly.','Throw one fake title-defense nod at the square and move on.',100,true),
  ((select id from pack_refs where slug = 'buenosaires'),'ba-congreso-pocket','Congreso Pocket',-34.6091,-58.3925,'Congreso','pocket','short-reset','Short pocket, center drag, and no help if you get soft.','Clock how fast the district mood changes when you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and keep rolling.',110,true),

  ((select id from pack_refs where slug = 'krakow'),'krakow-kazimierz-cut','Kazimierz Cut',50.0518,19.9450,'Kazimierz','street-cut','old-core','Tight blocks, river pull nearby, and no room for soft reads.','Clock the corner that feels more rider than visitor drift.','Touch the cut and trust the hard exit instantly.','Give the block one fake dispatch line and vanish.',10,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-old-town-seam','Old Town Seam',50.0617,19.9373,'Stare Miasto','seam','old-core-pressure','Old-core pressure and cleaner seams if you skip the obvious line.','Clock the least postcard corner and trust it over the obvious one.','Touch the seam and keep the cadence sharp.','Give the center one sarcastic compliment and move on.',20,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-podgorze-line','Podgorze Line',50.0436,19.9548,'Podgorze','line','river-pull','River edge, bridge reads, and no reward for drifting.','Clock the line riders actually trust when the block opens up.','Touch the line and commit before hesitation costs speed.','Throw one fake title-defense nod at the water and bounce.',30,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-zablocie-pocket','Zablocie Pocket',50.0494,19.9658,'Zablocie','pocket','warehouse-edge','Short pocket, warehouse edge, and one clean side if you read it early.','Clock how fast the block mood changes once you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and move on.',40,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-grzegorzki-seam','Grzegorzki Seam',50.0605,19.9574,'Grzegorzki','seam','tram-pressure','Fast city seam, tram pressure, and no help if you get soft.','Clock the side street that feels cleaner than the main road deserves.','Touch the seam and keep the pace blunt.','Make one fake race-radio call and disappear.',50,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-krowodrza-cut','Krowodrza Cut',50.0743,19.9238,'Krowodrza','street-cut','tram-lines','Fast blocks, tram lines, and no patience for bad timing.','Clock the lane locals still trust when the block gets loud.','Touch the cut and trust the cleaner side instantly.','Give the avenue one fake sponsor shout and get gone.',60,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-debniki-runup','Debniki Run-Up',50.0491,19.9258,'Debniki','run-up','bridge-gravity','River drag and awkward bridge approaches if you hesitate.','Clock the exact point the bridge starts owning the block.','Touch the run-up and commit before hesitation costs speed.','Throw one fake champion stare at the bridge and keep rolling.',70,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-planty-edge','Planty Edge',50.0629,19.9436,'Stare Miasto','edge','ring-pull','Ring edge, old-core pull, and better exits hiding in plain sight.','Clock the least polished useful corner and trust it.','Touch the edge and get back into the city before it softens you.','Rate the strip like a harsh race judge and cut out.',80,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-wolnica-pocket','Wolnica Pocket',50.0486,19.9443,'Kazimierz','pocket','short-reset','Short old-core pocket, fast exits, and no reward for drifting.','Clock how fast the block mood changes once you hit the pocket.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and move on.',90,true),
  ((select id from pack_refs where slug = 'krakow'),'krakow-vistula-seam','Vistula Seam',50.0482,19.9496,'Kazimierz','seam','river-pull','River seam, bridge pull, and no help if you drift.','Clock the exact point the water changes the feel of the block.','Touch the seam and trust the hard exit instantly.','Throw one fake title-defense nod at the river and bounce.',100,true)
on conflict (slug) do update
set
  pack_id = excluded.pack_id,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  district = excluded.district,
  category = excluded.category,
  vibe = excluded.vibe,
  hint = excluded.hint,
  task_local = excluded.task_local,
  task_fast = excluded.task_fast,
  task_chaotic = excluded.task_chaotic,
  sort_weight = excluded.sort_weight,
  is_active = excluded.is_active,
  updated_at = now();
