-- City batch seed: Vienna, Santos, Amsterdam, Paris, Milan, Bangkok, Taipei, Seoul

insert into public.city_packs (slug, name, route_note, finish_label, safety_note, is_active)
values
  ('vienna', 'Vienna', 'Canal seams, ring-road pressure, and side-street reads that only make sense once you commit.', 'Sheet clear, pace clean, city still judging.', 'Ride inside local laws, stay sharp around trams and traffic, and keep every task grounded in the real street.', true),
  ('santos', 'Santos', 'Port drag, beach wind, and block cuts that reward nerve more than polish.', 'Close the list, hold the line, tell the story later.', 'Ride inside local laws, stay aware in traffic, and keep every task realistic on live streets.', true),
  ('amsterdam', 'Amsterdam', 'Canal pressure, tram seams, and too many clean lines to hide a bad decision.', 'Sheet clear, city crossed, line owned.', 'Ride inside local laws, stay sharp around bikes, trams, and foot traffic, and keep every task safe.', true),
  ('paris', 'Paris', 'River cuts, ring chaos, and corners that only feel smart once you are already in them.', 'Close the sheet, kill the clock, leave the city talking.', 'Ride inside local laws, stay predictable in traffic, and keep every task grounded and safe.', true),
  ('milan', 'Milan', 'Fast cuts, tram lines, and corners that punish soft timing.', 'List clear, pace held, no soft excuses left.', 'Ride inside local laws, stay sharp around trams and traffic, and keep every task realistic.', true),
  ('bangkok', 'Bangkok', 'Heat, traffic drag, and lane calls that only feel clean if you trust them early.', 'Sheet clear, heat carried, line survived.', 'Ride inside local laws, stay alert in traffic, and keep every task safe and realistic.', true),
  ('taipei', 'Taipei', 'River seams, market cuts, and tight city rhythm hiding under clean surfaces.', 'Close the list, keep it neat, let the city stare back.', 'Ride inside local laws, stay sharp around scooters and traffic, and keep every task grounded.', true),
  ('seoul', 'Seoul', 'River lines, underpass pressure, and climbs that punish lazy reads.', 'List clear, lungs hot, line still clean.', 'Ride inside local laws, stay aware in traffic, and keep every task safe and doable.', true)
on conflict (slug) do update
set
  name = excluded.name,
  route_note = excluded.route_note,
  finish_label = excluded.finish_label,
  safety_note = excluded.safety_note,
  is_active = excluded.is_active,
  updated_at = now();

with pack_refs as (
  select id, slug from public.city_packs where slug in ('vienna', 'santos', 'amsterdam', 'paris', 'milan', 'bangkok', 'taipei', 'seoul')
)
insert into public.city_checkpoints (
  pack_id,
  slug,
  name,
  lat,
  lng,
  district,
  category,
  vibe,
  hint,
  task_local,
  task_fast,
  task_chaotic,
  sort_weight,
  is_active
)
values
  ((select id from pack_refs where slug = 'vienna'),'vienna-donaukanal-cut','Donaukanal Cut',48.2166,16.3794,'Leopoldstadt','canal-edge','wall-noise','Canal seam, wall noise, and no reason to get soft on the line.','Clock the first spot that feels more rider lane than postcard walk.','Touch the cut, pick the clean exit, and keep it sharp.','Give the canal one fake title stare and cut out.',10,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-praterstern-line','Praterstern Line',48.2196,16.3924,'Leopoldstadt','junction','circle-pressure','Open circle pressure and exits that punish lazy reads.','Clock the spoke locals actually trust here.','Touch the line and lock the next move in one glance.','Act like you planned that circle three lights ago and move on.',20,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-gumpendorfer-cut','Gumpendorfer Cut',48.1949,16.3498,'Mariahilf','street-cut','tram-drag','Tram drag and tight side exits.','Clock the corner that feels more daily grind than design.','Touch the cut and leave before the tram line traps you.','Give the block one fake sponsor tag and bounce.',30,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-ring-seam','Ring Seam',48.2058,16.3658,'Innere Stadt','seam','ring-pressure','Fast edge, bad angles, too much traffic to drift.','Clock the side lane that still feels usable under all that pressure.','Touch the seam and trust the hard exit immediately.','Mutter one fake dispatch line and disappear.',40,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-neubau-grid','Neubau Grid',48.2026,16.3497,'Neubau','grid','clean-sharp','Clean blocks, better cuts hiding underneath them.','Clock the least polished corner and trust it more than the clean one.','Touch the grid, keep your line blunt, and move.','Rate the block like a harsh race judge and leave.',50,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-belvedere-rise','Belvedere Rise',48.1913,16.3805,'Wieden','rise','short-wall','Short lift and zero free speed.','Notice where the block stops feeling flat and starts talking back.','Tag the rise and stay on top of it.','Treat that little wall like mountain-stage drama and keep rolling.',60,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-stephansplatz-seam','Stephansplatz Seam',48.2085,16.3731,'Innere Stadt','seam','old-core-pressure','Old-core seam, tourist drag nearby, cleaner exits if you trust the lane.','Clock the least postcard corner and trust it over the obvious one.','Touch the seam and cut before the square slows your read.','Give the center one fake title-defense nod and vanish.',70,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-schwedenplatz-line','Schwedenplatz Line',48.2112,16.3789,'Innere Stadt','line','canal-pressure','Fast edge, canal pull, and no room for bad timing.','Clock the line riders would actually trust when the block gets loud.','Touch the line and keep the cadence sharp.','Make one fake dispatch call and get gone.',80,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-karlsplatz-cut','Karlsplatz Cut',48.2006,16.3696,'Wieden','street-cut','junction-pressure','Open junction pressure and one clean move if you read it early.','Clock the least obvious useful exit and store it.','Touch the cut and trust the hard side immediately.','Give the square one sarcastic compliment and bounce.',90,true),
  ((select id from pack_refs where slug = 'vienna'),'vienna-mq-pocket','MQ Pocket',48.2031,16.3598,'Neubau','pocket','short-reset','Short pocket, clean exits, no reward for soft pacing.','Clock the corner that feels most like riders still own it.','Touch the pocket and leave before it flattens you.','Act like this was your lane all week and move on.',100,true),

  ((select id from pack_refs where slug = 'santos'),'santos-centro-cut','Centro Port Cut',-23.9335,-46.3281,'Centro','street-cut','port-drag','Port drag, worker blocks, no room for soft timing.','Clock the first corner that feels more port shift than beach city.','Touch the cut and punch the exit before the drag sets in.','Give the strip one fake sponsor shout and move.',10,true),
  ((select id from pack_refs where slug = 'santos'),'santos-gonzaga-line','Gonzaga Line',-23.9678,-46.3334,'Gonzaga','line','beach-drag','Beach drag nearby, cleaner blocks just off it.','Clock the lane locals use when they are not here for the coast.','Touch the line and get off the obvious route fast.','Give the avenue one sarcastic compliment and vanish.',20,true),
  ((select id from pack_refs where slug = 'santos'),'santos-boqueirao-cut','Boqueirao Cut',-23.9734,-46.3189,'Boqueirao','street-cut','fast-flats','Fast flats, tight reads, no reason to cruise.','Clock which corner feels most like a rider lane here.','Touch the cut, lock the clean seam, and go.','Make one fake radio call and keep pushing.',30,true),
  ((select id from pack_refs where slug = 'santos'),'santos-ponta-praia-edge','Ponta da Praia Edge',-23.9874,-46.3013,'Ponta da Praia','water-edge','open-drag','Open water edge and no help if you start admiring it.','Clock the least postcard angle and trust it more than the obvious one.','Touch the edge and get back into the city before it softens the move.','Throw one fake champion glare at the water and cut out.',40,true),
  ((select id from pack_refs where slug = 'santos'),'santos-macuco-pocket','Macuco Pocket',-23.9495,-46.3185,'Macuco','pocket','short-reset','Short calm patch, better exits if you trust the read.','Clock how fast the mood changes when you enter the block.','Touch the pocket and hit the fast side before it flattens you.','Act like this was your secret lane all week and move on.',50,true),
  ((select id from pack_refs where slug = 'santos'),'santos-cais-seam','Cais Seam',-23.9308,-46.3271,'Valongo','seam','dock-edge','Dock edge, long reads, and no reward for drifting.','Clock the exact point the city starts feeling more machine than coast.','Touch the seam and keep your cadence mean.','Quietly narrate the move like race radio and leave.',60,true),
  ((select id from pack_refs where slug = 'santos'),'santos-jose-menino-edge','Jose Menino Edge',-23.967,-46.3472,'Jose Menino','water-edge','rail-drag','Beach edge, rail drag, and a line that punishes lazy exits.','Clock the corner that feels more weekday rider than boardwalk drift.','Touch the edge and cut back in before the coast slows you down.','Give the water one fake title-defense stare and bounce.',70,true),
  ((select id from pack_refs where slug = 'santos'),'santos-pompeia-cut','Pompeia Cut',-23.9648,-46.3414,'Pompeia','street-cut','fast-flats','Fast flats, side-street rhythm, and no reward for coasting.','Clock the lane locals actually trust when they are moving fast.','Touch the cut and lock the clean seam in one glance.','Make one fake radio call and keep pushing.',80,true),
  ((select id from pack_refs where slug = 'santos'),'santos-campo-grande-line','Campo Grande Line',-23.9537,-46.3397,'Campo Grande','line','worker-rush','Worker blocks and cleaner exits hiding off the loud roads.','Clock the block that feels more rider lane than family errand.','Touch the line and leave before the big road drags you in.','Give the avenue one sarcastic compliment and vanish.',90,true),
  ((select id from pack_refs where slug = 'santos'),'santos-vila-mathias-seam','Vila Mathias Seam',-23.9486,-46.3328,'Vila Mathias','seam','tight-fast','Tight city seam and no reason to ride polite through it.','Clock the least polished useful corner and trust it.','Touch the seam and keep the cadence sharp.','Give the block one fake alleycat sponsor tag and move.',100,true),
  ((select id from pack_refs where slug = 'santos'),'santos-aparecida-pocket','Aparecida Pocket',-23.973,-46.3075,'Aparecida','pocket','coast-falloff','Short pocket, quick exits, no help if you start admiring the coast.','Clock how fast the beach mood falls off when you hit the pocket.','Touch the pocket and hit the fast side before it softens you.','Act like this was your lane all week and keep rolling.',110,true),
  ((select id from pack_refs where slug = 'santos'),'santos-embare-run','Embare Run',-23.9797,-46.3129,'Embare','water-edge','water-drag','Water drag nearby, cleaner blocks if you leave the obvious line early.','Clock the least postcard corner and trust it over the clean one.','Touch the run and get back into the city before the coast wins.','Throw one fake champion glare at the beach and cut out.',120,true),

  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-jordaan-cut','Jordaan Cut',52.3764,4.8836,'Jordaan','street-cut','canal-pressure','Canal edges, tight corners, too many almost-clean exits.','Clock the lane that feels more messenger than postcard drift.','Touch the cut and keep off the obvious tourist line.','Give the canal one fake title-defense stare and bounce.',10,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-westerpark-line','Westerpark Line',52.3872,4.8748,'Westerpark','line','open-fast','Open line, cleaner if you leave it on time.','Clock the exact point where the park stops helping the move.','Touch the line and snap back into the grid before it softens you.','Throw one fake sponsor shout at the grass and go.',20,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-de-pijp-grid','De Pijp Grid',52.3547,4.8923,'De Pijp','grid','dense-rhythm','Fast blocks, crowded reads, no patience for bad timing.','Clock the first cross street riders actually trust here.','Touch the grid and keep the line tight.','Make one fake dispatch call and get gone.',30,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-oost-seam','Oost Seam',52.3608,4.9302,'Oost','seam','water-read','Water seams and long reads under bike pressure.','Clock what feels most local and least polished on the block.','Touch the seam and trust the cleaner side instantly.','Give the strip one fake podium nod and disappear.',40,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-noord-ferry-edge','Noord Ferry Edge',52.3840,4.9003,'Noord','water-edge','ferry-drag','Waterfront drag and exits that punish lazy reads.','Clock the exact point the ferry zone stops helping and starts baiting you.','Touch the edge and cut back into the city fast.','Give the water one sarcastic compliment and bounce.',50,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-museum-backline','Museum Backline',52.3583,4.8811,'Museumkwartier','backstreet','pretty-trap','Pretty trap, better cuts hiding off the main pull.','Find the least polished corner and trust it over the obvious one.','Touch the backline and leave before the block goes soft.','Rate the block out of ten like a harsh sponsor and move.',60,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-nieuwmarkt-seam','Nieuwmarkt Seam',52.3725,4.9006,'Centrum','seam','old-core-pressure','Dense old-core seam and no reason to drift through it.','Clock the lane that feels more messenger than postcard drift.','Touch the seam and trust the hard exit instantly.','Give the square one fake sponsor shout and vanish.',70,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-rembrandt-line','Rembrandt Line',52.3669,4.8966,'Centrum','line','tram-pressure','Fast city line, tram pressure, and no patience for bad timing.','Clock the cross street riders actually trust here.','Touch the line and keep the pace blunt.','Make one fake dispatch call and keep rolling.',80,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-leidse-cut','Leidse Cut',52.3649,4.8820,'Centrum','street-cut','crowd-pressure','Crowd pressure and cleaner cuts hiding off the obvious line.','Find the least polished corner and trust it over the clean one.','Touch the cut and get gone before the block clogs up.','Give the strip one fake podium nod and disappear.',90,true),
  ((select id from pack_refs where slug = 'amsterdam'),'amsterdam-wallen-pocket','Wallen Pocket',52.3731,4.8956,'Centrum','pocket','tight-fast','Tight old-core pocket, zero room for soft reads.','Clock the lane locals still use when the block gets loud.','Touch the pocket and hit the quick side before it softens you.','Act like this was your lane all week and move on.',100,true),

  ((select id from pack_refs where slug = 'paris'),'paris-canal-cut','Canal Saint-Martin Cut',48.8721,2.3659,'Canal Saint-Martin','canal-edge','canal-drag','Canal drag, bridge seams, and too many soft exits.','Clock which side feels more rider than weekend crowd.','Touch the cut and leave before the canal flattens your move.','Throw one fake title-defense nod at the water and go.',10,true),
  ((select id from pack_refs where slug = 'paris'),'paris-bastille-line','Bastille Line',48.8532,2.3692,'Bastille','line','ring-pressure','Fast blocks, ring pressure, no room for soft timing.','Clock the side lane locals actually use here.','Touch the line and keep the pace blunt.','Make one fake race-radio call and keep rolling.',20,true),
  ((select id from pack_refs where slug = 'paris'),'paris-belleville-rise','Belleville Rise',48.8729,2.3842,'Belleville','rise','hill-bite','Short climb pressure and no free speed.','Notice where the block stops feeling flat and starts fighting back.','Tag the rise and stay on top of the wall.','Treat that lift like mountain-stage drama and move on.',30,true),
  ((select id from pack_refs where slug = 'paris'),'paris-republique-seam','Republique Seam',48.8674,2.3631,'Republique','seam','square-pull','Open square pull, better seams just off it.','Clock the least obvious useful exit and store it.','Touch the seam and cut before the square drags you in.','Give the square one fake sponsor shout and disappear.',40,true),
  ((select id from pack_refs where slug = 'paris'),'paris-left-bank-cut','Left Bank Cut',48.8483,2.3474,'Latin Quarter','street-cut','old-block','Tight old blocks and no reason to ride polite.','Clock the first corner that feels more rider than cafe line.','Touch the cut and keep it neat, not soft.','Give the block one fake style score and go.',50,true),
  ((select id from pack_refs where slug = 'paris'),'paris-bercy-edge','Bercy Edge',48.8397,2.3824,'Bercy','river-edge','river-read','River drag and long reads if you switch off.','Clock the exact moment the river starts changing the block mood.','Touch the edge and trust the hard exit.','Quietly narrate the move like you own the city and leave.',60,true),
  ((select id from pack_refs where slug = 'paris'),'paris-hotel-de-ville-line','Hotel de Ville Line',48.8568,2.3518,'Hotel de Ville','line','old-core-pressure','Old-core line, river pressure nearby, and no reward for drifting.','Clock the side lane that feels more rider than city hall spill.','Touch the line and keep the cadence sharp.','Give the block one fake title-defense nod and bounce.',70,true),
  ((select id from pack_refs where slug = 'paris'),'paris-marais-cut','Marais Cut',48.8584,2.3622,'Le Marais','street-cut','tight-old-core','Tight old blocks and cleaner exits than they want to admit.','Clock the least polished useful corner and trust it.','Touch the cut and leave before the block goes soft.','Make one fake dispatch call and disappear.',80,true),
  ((select id from pack_refs where slug = 'paris'),'paris-chatelet-seam','Chatelet Seam',48.8590,2.3470,'Chatelet','seam','transit-pressure','Transit pull, bad angles, and one clean move if you stay blunt.','Clock the line riders actually trust when the square gets loud.','Touch the seam and trust the hard exit instantly.','Give the whole block one sarcastic compliment and move on.',90,true),
  ((select id from pack_refs where slug = 'paris'),'paris-saint-germain-pocket','Saint-Germain Pocket',48.8542,2.3338,'Saint-Germain','pocket','short-reset','Short pocket, quick exits, and no need for cafe pacing.','Clock how fast the mood changes once you hit the pocket.','Touch the pocket and hit the fast side before it flattens you.','Act like this was your lane all week and bounce.',100,true),

  ((select id from pack_refs where slug = 'milan'),'milan-navigli-cut','Navigli Cut',45.4526,9.1742,'Navigli','canal-edge','canal-drag','Canal drag, bar spill, and cleaner seams if you trust the read.','Clock the lane locals use when they are not here for the scene.','Touch the cut and leave before the canal softens the move.','Give the water one fake sponsor nod and bounce.',10,true),
  ((select id from pack_refs where slug = 'milan'),'milan-isola-line','Isola Line',45.4885,9.1887,'Isola','line','rail-pressure','Fast line, rail pressure, good exits hiding in plain sight.','Clock the first corner that feels more rider than office spill.','Touch the line and keep the cadence sharp.','Make one fake dispatch call and keep moving.',20,true),
  ((select id from pack_refs where slug = 'milan'),'milan-porta-romana-rise','Porta Romana Rise',45.4546,9.2044,'Porta Romana','rise','short-wall','Slight lift, fast exits, no help if you go soft.','Clock where the block stops looking flat and starts talking back.','Tag the rise and punch through it clean.','Treat that wall like a stage finish and ride out.',30,true),
  ((select id from pack_refs where slug = 'milan'),'milan-citta-studi-cut','Citta Studi Cut',45.4789,9.2283,'Citta Studi','street-cut','long-read','Long blocks, quick reads, no reason to drift.','Clock which side street feels most local without trying.','Touch the cut and trust the clean seam instantly.','Rate the strip like a harsh race judge and go.',40,true),
  ((select id from pack_refs where slug = 'milan'),'milan-garibaldi-seam','Garibaldi Seam',45.4851,9.1867,'Porta Garibaldi','seam','machine-rhythm','Machine rhythm, tram edges, and bad angles if you hesitate.','Clock the lane that still feels more messenger than business district.','Touch the seam and keep the line blunt.','Give the glass one sarcastic compliment and disappear.',50,true),
  ((select id from pack_refs where slug = 'milan'),'milan-ticinese-pocket','Ticinese Pocket',45.4563,9.1811,'Ticinese','pocket','short-reset','Short calm pocket, sharp exits if your head is on right.','Clock how fast the block mood changes once you enter it.','Touch the pocket and leave before it softens you.','Act like this was your lane all week and bounce.',60,true),
  ((select id from pack_refs where slug = 'milan'),'milan-duomo-seam','Duomo Seam',45.4644,9.1916,'Centro Storico','seam','center-pressure','Center pressure, tourist drag nearby, and better seams off the obvious line.','Clock the least postcard corner and trust it over the clean one.','Touch the seam and get out before the center slows your read.','Give the square one fake title nod and disappear.',70,true),
  ((select id from pack_refs where slug = 'milan'),'milan-brera-cut','Brera Cut',45.4715,9.1886,'Brera','street-cut','old-core-rhythm','Tight old-core cut and no room for soft timing.','Clock the lane that feels more rider than gallery drift.','Touch the cut and trust the cleaner side instantly.','Make one fake dispatch call and keep moving.',80,true),
  ((select id from pack_refs where slug = 'milan'),'milan-missori-line','Missori Line',45.4608,9.1889,'Centro Storico','line','tram-pressure','Fast center line, tram pressure, and no reward for drifting.','Clock the side lane riders actually trust here.','Touch the line and keep the cadence sharp.','Give the avenue one sarcastic compliment and bounce.',90,true),
  ((select id from pack_refs where slug = 'milan'),'milan-porta-venezia-pocket','Porta Venezia Pocket',45.4781,9.2055,'Porta Venezia','pocket','short-reset','Short pocket, quick exits, and one clean move if you read it early.','Clock how fast the district mood changes when you enter it.','Touch the pocket and leave before it softens you.','Act like this was your lane all week and move on.',100,true),

  ((select id from pack_refs where slug = 'bangkok'),'bangkok-ari-cut','Ari Cut',13.7797,100.5439,'Ari','street-cut','heat-pressure','Heat, traffic, and tight block reads under scooter pressure.','Clock the first lane that feels more rider than cafe strip.','Touch the cut and keep the pace sharp.','Give the block one fake podium nod and leave.',10,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-siam-seam','Siam Seam',13.7467,100.5348,'Siam','seam','dense-flow','Dense movement, no clean mistakes, one usable seam if you trust it.','Clock the least obvious useful line through the block.','Touch the seam and leave before the crowd wins.','Mutter one fake dispatch line and get out.',20,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-yaowarat-line','Yaowarat Line',13.7396,100.5107,'Chinatown','line','worker-rush','Tight food drag, hot streets, no softness allowed.','Clock the first corner that feels more worker rush than visitor drift.','Touch the line and trust the hard exit.','Give the strip one fake sponsor tag and vanish.',30,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-khlong-toei-edge','Khlong Toei Edge',13.7235,100.5532,'Khlong Toei','edge','market-pressure','Market pressure, heavy traffic, and no reward for drifting.','Clock the exact point the block starts feeling more machine than city.','Touch the edge and keep your line blunt.','Throw one fake champion stare at the traffic and move.',40,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-bang-rak-cut','Bang Rak Cut',13.7246,100.5215,'Bang Rak','street-cut','river-drag','River drag nearby, cleaner blocks just off the obvious line.','Clock the least polished corner and trust it over the clean one.','Touch the cut and leave before the river softens you.','Give the block a fake style score and bounce.',50,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-chatuchak-pocket','Chatuchak Pocket',13.7991,100.5502,'Chatuchak','pocket','open-fast','Open pocket, fast exits, no reason to cruise.','Clock how quickly the mood changes when you enter the zone.','Touch the pocket and hit the fast side before it flattens you.','Act like this was your training lane all month and move on.',60,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-banglamphu-cut','Banglamphu Cut',13.759,100.4975,'Phra Nakhon','street-cut','old-core','Old-city blocks, heat, and no room for soft reads.','Clock the lane that feels more rider than backpack drift.','Touch the cut and keep the pace sharp through the heat.','Give the block one fake dispatch line and disappear.',70,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-sam-yot-seam','Sam Yot Seam',13.7437,100.5033,'Phra Nakhon','seam','dense-old-core','Dense old-core seam and one clean move if you trust it early.','Clock the least obvious useful line through the block.','Touch the seam and leave before the traffic wins.','Mutter one fake race-radio call and get gone.',80,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-talat-noi-line','Talat Noi Line',13.7364,100.5131,'Samphanthawong','line','workshop-rush','Workshop blocks, river air, and no reward for drifting.','Clock the corner that feels most like regulars still own it.','Touch the line and trust the hard exit instantly.','Give the strip one fake sponsor nod and vanish.',90,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-ratchathewi-cut','Ratchathewi Cut',13.7541,100.5316,'Ratchathewi','street-cut','rail-pressure','Fast blocks, rail pressure, and too many almost-clean exits.','Clock the lane riders actually trust when the block gets loud.','Touch the cut and keep the line blunt.','Give the avenue one sarcastic compliment and move on.',100,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-chula-pocket','Chula Pocket',13.7373,100.5284,'Pathum Wan','pocket','short-reset','Short pocket, fast exits, no reason to coast.','Clock how fast the district mood changes when you enter it.','Touch the pocket and hit the quick side before it softens you.','Act like this was your training lane all week and bounce.',110,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-saphan-taksin-runup','Saphan Taksin Run-Up',13.7184,100.5142,'Bang Rak','bridge-runup','river-gravity','River drag, bridge gravity, and awkward approach choices.','Clock the exact point the bridge starts owning the block.','Touch the run-up and commit before hesitation costs speed.','Throw one fake champion stare at the river and keep moving.',120,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-democracy-line','Democracy Line',13.7579,100.5016,'Phra Nakhon','line','old-core-pressure','Old-core pressure, open junction, no help if you drift.','Clock the line that feels more rider than ceremony route.','Touch the line and lock the next move instantly.','Give the circle one fake title nod and get gone.',130,true),
  ((select id from pack_refs where slug = 'bangkok'),'bangkok-giant-swing-cut','Giant Swing Cut',13.7527,100.5015,'Phra Nakhon','street-cut','tight-old-core','Tight old-core cut and no reason to ride polite.','Clock the least polished useful corner and trust it.','Touch the cut and keep the pace blunt.','Make one fake dispatch call and disappear.',140,true),

  ((select id from pack_refs where slug = 'taipei'),'taipei-ximending-cut','Ximending Cut',25.0439,121.5078,'Wanhua','street-cut','crowd-pressure','Dense foot flow and side seams that only work if you trust them early.','Clock the lane riders would use when they are not here to hang out.','Touch the cut and get gone before the crowd drags your pace down.','Give the block one fake title-defense nod and bounce.',10,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-dadaocheng-line','Dadaocheng Line',25.0567,121.5083,'Datong','line','old-block','River pull nearby, old blocks, cleaner reads than they look.','Clock the least polished useful corner and trust it.','Touch the line and keep the move blunt.','Make one fake dispatch call and disappear.',20,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-zhongshan-seam','Zhongshan Seam',25.0534,121.5222,'Zhongshan','seam','city-rhythm','Fast city rhythm, long blocks, too many almost-good exits.','Clock the cross street that feels most rider here.','Touch the seam and trust the clean side instantly.','Give the avenue one sarcastic compliment and cut out.',30,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-gongguan-pocket','Gongguan Pocket',25.0159,121.5333,'Zhongzheng','pocket','short-reset','Short pocket, strong exits, no free speed.','Clock how fast the block mood changes once you enter it.','Touch the pocket and leave before it softens you.','Act like this was your lane all week and move on.',40,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-xinyi-runup','Xinyi Run-Up',25.0335,121.5645,'Xinyi','run-up','machine-rhythm','Wide blocks, machine rhythm, awkward approach choices.','Clock the exact point the district starts feeling more machine than city.','Touch the run-up and keep the line cleaner than traffic deserves.','Throw one fake champion stare at the towers and go.',50,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-heping-river-edge','Heping River Edge',25.0236,121.5446,'Da''an','river-edge','water-read','River seam and no help if you start admiring the open line.','Clock the exact moment the water changes the sound of the block.','Touch the edge and cut back into the city before it softens you.','Give the river one fake sponsor nod and disappear.',60,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-daan-forest-cut','Da''an Forest Cut',25.033,121.5346,'Da''an','street-cut','park-edge','Park edge, city rhythm, and no reward for getting soft.','Clock the lane that feels more weekday rider than weekend stroll.','Touch the cut and get back into the grid before the park flattens you.','Give the trees one fake sponsor shout and bounce.',70,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-yongkang-pocket','Yongkang Pocket',25.0296,121.5293,'Da''an','pocket','short-reset','Short pocket and cleaner exits than the block wants to admit.','Clock the least polished useful corner and trust it.','Touch the pocket and hit the quick side before it softens you.','Act like this was your lane all week and keep moving.',80,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-guting-line','Guting Line',25.0261,121.5224,'Zhongzheng','line','city-rhythm','Fast city line and no patience for lazy timing.','Clock the cross street riders would actually trust here.','Touch the line and keep the cadence sharp.','Make one fake dispatch call and disappear.',90,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-songshan-seam','Songshan Seam',25.0488,121.5773,'Songshan','seam','market-pressure','Long blocks, market pressure, and one clean move if you read it early.','Clock the first corner that feels more rider than shopper.','Touch the seam and trust the cleaner side instantly.','Give the strip one fake podium nod and get gone.',100,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-sun-yat-sen-run','Sun Yat-Sen Run',25.0417,121.5602,'Xinyi','run-up','tower-pressure','Wide lanes, tower pressure, and no need for a scenic pause.','Clock the least polished edge under all that big-city gloss.','Touch the run and keep the line cleaner than traffic deserves.','Throw one fake champion glare at the towers and move on.',110,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-ningxia-edge','Ningxia Edge',25.0565,121.5157,'Datong','edge','night-market-drag','Dense edge, night-market drag, and no reward for hesitation.','Clock the lane locals actually use when the block gets crowded.','Touch the edge and leave before the crowd wins.','Give the block one fake title-defense nod and cut out.',120,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-city-hall-seam','City Hall Seam',25.0409,121.5676,'Xinyi','seam','tower-drag','Wide lanes, tower drag, and no reward for lazy timing.','Clock the side lane that feels cleaner than the district deserves.','Touch the seam and stay sharp through the machine rhythm.','Give the towers one sarcastic compliment and move on.',130,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-linjiang-cut','Linjiang Cut',25.0309,121.5548,'Da''an','street-cut','market-pull','Dense blocks, market pull, and one hard exit if you trust it.','Clock the lane riders would actually use when the block gets crowded.','Touch the cut and leave before the crowd drags your pace down.','Give the block one fake podium nod and bounce.',140,true),
  ((select id from pack_refs where slug = 'taipei'),'taipei-xinyi-anhe-line','Xinyi Anhe Line',25.0334,121.552,'Da''an','line','city-rhythm','Fast city line and no patience for bad reads.','Clock the cross street that feels most like a rider call here.','Touch the line and trust the clean side instantly.','Make one fake race-radio call and keep rolling.',150,true),

  ((select id from pack_refs where slug = 'seoul'),'seoul-euljiro-cut','Euljiro Cut',37.5667,126.9911,'Jung-gu','street-cut','machine-block','Machine blocks, tight alleys, and no free mistakes.','Clock the first alley that feels more rider than office spill.','Touch the cut and trust the hard exit immediately.','Give the block one fake dispatch line and bounce.',10,true),
  ((select id from pack_refs where slug = 'seoul'),'seoul-hongdae-line','Hongdae Line',37.5563,126.9237,'Mapo-gu','line','crowd-pressure','Crowd pressure, side seams, cleaner if you ride it blunt.','Clock the lane locals actually trust when the block gets loud.','Touch the line and cut before the crowd wins.','Give the strip one fake style score and move on.',20,true),
  ((select id from pack_refs where slug = 'seoul'),'seoul-itaewon-rise','Itaewon Rise',37.5342,126.9947,'Yongsan-gu','rise','short-wall','Short climb and no free speed anywhere near it.','Notice where the block stops feeling flat and starts biting back.','Tag the rise and keep your cadence mean.','Treat that little wall like mountain-stage drama and keep rolling.',30,true),
  ((select id from pack_refs where slug = 'seoul'),'seoul-seongsu-seam','Seongsu Seam',37.5446,127.0557,'Seongdong-gu','seam','warehouse-edge','Warehouse edge, river pull, and no room for soft timing.','Clock the least polished useful corner on the block.','Touch the seam and lock the next move fast.','Give the strip one fake sponsor shout and vanish.',40,true),
  ((select id from pack_refs where slug = 'seoul'),'seoul-yeouido-run','Yeouido Run',37.5273,126.9245,'Yeongdeungpo-gu','waterline','river-drag','Waterline temptation and exits that punish lazy reads.','Clock the exact point the open line stops helping the move.','Touch the run and get back into the city before it softens you.','Throw one fake champion glare at the river and cut out.',50,true),
  ((select id from pack_refs where slug = 'seoul'),'seoul-jamsil-pocket','Jamsil Pocket',37.5145,127.1059,'Songpa-gu','pocket','wide-fast','Wide blocks, quick exits, no reward for drifting.','Clock how fast the district mood changes once you enter the block.','Touch the pocket and keep the line neat, not polite.','Act like this was your lane all week and move on.',60,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-gwanghwamun-grid','Gwanghwamun Grid',37.5759,126.9768,'Jongno-gu','grid','open-pressure','Open government blocks and cleaner cuts hiding off the obvious line.','Clock the lane that feels more rider than ceremony route.','Touch the grid and keep the pace blunt.','Give the boulevard one sarcastic compliment and move on.',70,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-ikseon-pocket','Ikseon Pocket',37.574,126.9893,'Jongno-gu','pocket','tight-fast','Short pocket, dense blocks, no room for soft timing.','Clock the least polished useful corner and trust it.','Touch the pocket and hit the quick side before it softens you.','Act like this was your lane all week and bounce.',80,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-cheonggyecheon-seam','Cheonggyecheon Seam',37.5692,127.001,'Jung-gu','seam','water-underpass','Water seam, underpass pressure, and one clean move if you stay sharp.','Clock the exact point the water changes the mood of the block.','Touch the seam and trust the hard exit immediately.','Throw one fake champion glare at the water and cut out.',90,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-dongdaemun-runup','Dongdaemun Run-Up',37.571,127.0095,'Jung-gu','run-up','big-road-pressure','Big-road pressure and awkward approach choices that punish hesitation.','Clock the line riders actually trust when the block opens up.','Touch the run-up and commit before the traffic thinks for you.','Make one fake dispatch call and keep rolling.',100,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-seochon-cut','Seochon Cut',37.579,126.9708,'Jongno-gu','street-cut','old-lane','Old-lane cut and no reason to ride polite through it.','Clock the corner that feels most like locals still own it.','Touch the cut and leave before the lane gets soft.','Give the block one fake sponsor tag and vanish.',110,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-seoul-station-line','Seoul Station Line',37.5547,126.9707,'Yongsan-gu','line','station-pressure','Station pressure, fast reads, and no reward for drifting.','Clock the side street that feels cleaner than the block deserves.','Touch the line and keep the cadence mean.','Rate the whole strip like a harsh race judge and move on.',120,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-jonggak-seam','Jonggak Seam',37.5704,126.983,'Jongno-gu','seam','signal-pressure','Signal pressure, office spill, and one clean seam if your head stays on.','Clock the lane that feels more rider than office break.','Touch the seam and trust the hard exit immediately.','Give the block one fake dispatch line and vanish.',130,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-anguk-line','Anguk Line',37.5765,126.9853,'Jongno-gu','line','old-core-rhythm','Old-core line, quick corners, and no help if you get soft.','Clock the corner that feels most like locals still own it.','Touch the line and keep the move neat, not polite.','Act like this was always your lane and keep moving.',140,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-city-hall-cut','City Hall Cut',37.5658,126.9771,'Jung-gu','street-cut','center-pressure','Center cut, office pressure, and no reason to drift.','Clock the least obvious useful exit in the middle of all that motion.','Touch the cut and trust the hard side instantly.','Give the block one fake title-defense nod and bounce.',150,true)
  ,((select id from pack_refs where slug = 'seoul'),'seoul-jongno-pocket','Jongno Pocket',37.5709,126.9796,'Jongno-gu','pocket','short-reset','Short old-core pocket, fast exits, and no help if you go soft.','Clock how fast the block mood changes once you hit the pocket.','Touch the pocket and keep the pace blunt.','Make one fake dispatch call and vanish.',160,true)
on conflict (slug) do update
set
  pack_id = excluded.pack_id,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  district = excluded.district,
  category = excluded.category,
  vibe = excluded.vibe,
  hint = excluded.hint,
  task_local = excluded.task_local,
  task_fast = excluded.task_fast,
  task_chaotic = excluded.task_chaotic,
  sort_weight = excluded.sort_weight,
  is_active = excluded.is_active,
  updated_at = now();
