-- Wave 1 Alleycat city packs
-- Seeds Berlin, London, and Tokyo into city_packs + city_checkpoints.

insert into public.city_packs (slug, name, route_note, finish_label, safety_note, is_active)
values
  (
    'berlin',
    'Berlin',
    'Backstreets, bridge wind, blunt cut-throughs. Skip the postcard line and ride the parts that answer back.',
    'List clear, clock dead, one decent story earned.',
    'Ride inside local laws, stay sharp in traffic, and keep every task safe and doable.',
    true
  ),
  (
    'london',
    'London',
    'Station pressure, canal seams, bad choices that become good ones if you commit early enough.',
    'Clear the sheet, kill the clock, act like you planned it all.',
    'Ride clean, stay predictable, and do not force moves through crowds.',
    true
  ),
  (
    'tokyo',
    'Tokyo',
    'Precision outside, alley instincts underneath. Keep it exact, keep it moving, and do not get hypnotized by the lights.',
    'Close the run, keep the face straight, tell the story later.',
    'Respect the street, stay predictable in traffic, and keep every task safe and realistic.',
    true
  )
on conflict (slug) do update
set
  name = excluded.name,
  route_note = excluded.route_note,
  finish_label = excluded.finish_label,
  safety_note = excluded.safety_note,
  is_active = excluded.is_active,
  updated_at = now();

with pack_refs as (
  select id, slug from public.city_packs where slug in ('berlin', 'london', 'tokyo')
)
insert into public.city_checkpoints (
  pack_id,
  slug,
  name,
  lat,
  lng,
  district,
  category,
  vibe,
  hint,
  task_local,
  task_fast,
  task_chaotic,
  sort_weight,
  is_active
)
values
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-alex-clock',
    'Alexanderplatz World Clock',
    52.521918,
    13.413215,
    'Mitte',
    'square',
    'crowd-pressure',
    'Meet the spinning time zones.',
    'Clock one city name on the clock you would actually ride to and remember why.',
    'Touch the square, lock the exit, and move before the crowd drags your speed down.',
    'Stand dead serious for one fake world-title photo in your head, then leave before the square wins.',
    10,
    true
  ),
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-obernbaum',
    'Oberbaum Bridge',
    52.501775,
    13.446943,
    'Friedrichshain-Kreuzberg',
    'bridge',
    'windy',
    'Brick towers, river wind, no straight answers.',
    'Clock which side of the river sounds louder and decide what that says about the night.',
    'Hit the bridge, read the exit, and get off it before the wind starts negotiating.',
    'Give the bridge one sarcastic nod like it personally tried to humble you, then roll out.',
    20,
    true
  ),
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-tempelhof',
    'Tempelhofer Feld Gate',
    52.473629,
    13.403419,
    'Tempelhof',
    'open-space',
    'runway',
    'Runway energy without the planes.',
    'Spot one thing only Tempelhof could make feel this wide and still this tense.',
    'Touch the gate, breathe once, and throw yourself back into the grid.',
    'Quietly announce a fake takeoff clearance to yourself and leave before anyone notices.',
    30,
    true
  ),
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-luftbruecke',
    'Platz der Luftbruecke Edge',
    52.4849,
    13.3852,
    'Tempelhof',
    'junction',
    'circle-pressure',
    'Big circle energy, quick exits, zero reason to drift.',
    'Clock which side of the circle feels calmer than it should.',
    'Touch the edge, lock your escape, and keep your pace honest.',
    'Give the roundabout one fake salute and cut before it gets ceremonial.',
    35,
    true
  ),
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-victoriapark-rise',
    'Victoriapark Lower Rise',
    52.4885,
    13.3927,
    'Kreuzberg',
    'rise',
    'short-climb',
    'Short climb pressure and a clean exit if you read it right.',
    'Notice the first point where the block stops feeling flat.',
    'Tag the rise, breathe once, and punch out before it drags on.',
    'Act like that tiny lift was alpine drama, then move on.',
    37,
    true
  ),
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-mauerpark',
    'Mauerpark Amphitheatre',
    52.541541,
    13.402147,
    'Prenzlauer Berg',
    'bowl',
    'messy',
    'Concrete bowl, noise, and open edges.',
    'Read the mood of the park in three words and make at least one of them unfair.',
    'Drop in, read the crowd fast, and leave before the slowdown reaches your legs.',
    'Rate the current energy like a terrible talent show judge and move on immediately.',
    40,
    true
  ),
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-tiergarten',
    'Tiergarten S-Bend',
    52.51417,
    13.36652,
    'Tiergarten',
    'cut-through',
    'quiet-reset',
    'A soft patch inside a hard city.',
    'Notice the first sound that disappears when the trees finally catch you.',
    'Use the calm as a reset seam, then get back to work without getting lazy.',
    'Pick your exit purely by instinct and defend it like it was a tactical masterstroke.',
    50,
    true
  ),
  (
    (select id from pack_refs where slug = 'berlin'),
    'berlin-kotti',
    'Kotti Ring Edge',
    52.4996,
    13.4186,
    'Kreuzberg',
    'junction',
    'hot',
    'Too much movement, exactly the right amount of pressure.',
    'Clock the sketchiest calm-looking corner and remember it for later.',
    'Touch the edge, pick the cleanest escape, and do not let the ring slow your thinking.',
    'Mutter a fake apology to the traffic, then cut out like you meant no harm.',
    60,
    true
  ),

  (
    (select id from pack_refs where slug = 'london'),
    'london-somerset',
    'Somerset House Courtyard',
    51.511463,
    -0.117422,
    'Central London',
    'courtyard',
    'stone-open',
    'Open stone and fast exits.',
    'Find the strongest line through the courtyard and keep it in your head for later.',
    'Touch the square, scan the exits once, and commit before the place flattens you.',
    'Give the courtyard one absurdly formal nod like it owes you respect, then bounce.',
    10,
    true
  ),
  (
    (select id from pack_refs where slug = 'london'),
    'london-columbia-road',
    'Columbia Road',
    51.529274,
    -0.071812,
    'Bethnal Green',
    'street',
    'tight',
    'Tight streets with market energy.',
    'Clock one storefront detail that feels more local than the whole road wants to admit.',
    'Read the street in one pass and keep rolling before the lane decides for you.',
    'Quietly judge the whole block like a fashion editor with zero qualifications, then leave.',
    20,
    true
  ),
  (
    (select id from pack_refs where slug = 'london'),
    'london-waterloo',
    'Waterloo Station Arch',
    51.503334,
    -0.113122,
    'Waterloo',
    'station-edge',
    'commuter-pressure',
    'Crowd pressure and decision pressure.',
    'Pick the exit you would trust if the weather got worse in ten seconds.',
    'Touch the arch zone and leave before the commuter tide starts billing you for it.',
    'Count the opposing flows, pretend you loved the chaos, and cut through anyway.',
    30,
    true
  ),
  (
    (select id from pack_refs where slug = 'london'),
    'london-regents',
    'Regent''s Canal Towpath Entry',
    51.536578,
    -0.103717,
    'Islington',
    'towpath',
    'hidden-seam',
    'A hidden seam in the city.',
    'Notice the first thing that makes the city feel quieter without feeling safe.',
    'Use the canal as a reset point, then re-enter clean with no wasted movement.',
    'Decide out loud whether this was a shortcut or a trap, then commit to your answer.',
    40,
    true
  ),
  (
    (select id from pack_refs where slug = 'london'),
    'london-greenwich',
    'Greenwich Foot Tunnel North Entrance',
    51.500732,
    -0.008077,
    'Greenwich',
    'river-edge',
    'history-weird',
    'A route choice with history baked in.',
    'Mark the strangest contrast between river traffic and street traffic.',
    'Hit the entrance, make the call fast, and keep momentum on your side.',
    'Throw one fake heroic stare at the river and move before it gets embarrassing.',
    50,
    true
  ),
  (
    (select id from pack_refs where slug = 'london'),
    'london-soho',
    'Soho Seven Dials',
    51.513628,
    -0.128111,
    'Soho',
    'junction',
    'choice-overload',
    'Too many spokes, which is exactly the point.',
    'Choose the spoke that best matches your current mood and do not justify it.',
    'Read the junction fast and trust your cut before the taxis start thinking for you.',
    'Pick the fun-looking wrong line in your head, then take the smart one in real life.',
    60,
    true
  ),

  (
    (select id from pack_refs where slug = 'tokyo'),
    'tokyo-shibuya-scramble',
    'Shibuya Scramble Edge',
    35.6595,
    139.7005,
    'Shibuya',
    'crossing',
    'human-chaos',
    'Too many flows, too many faces, no sympathy.',
    'Clock the cleanest gap in the human mess and remember it like it owes you money.',
    'Hit the edge, pick your exit in one glance, and leave before hesitation gets expensive.',
    'Give the crossing your best fake race-face for two seconds, then vanish like nothing happened.',
    10,
    true
  ),
  (
    (select id from pack_refs where slug = 'tokyo'),
    'tokyo-yoyogi-entry',
    'Yoyogi Park South Gate',
    35.6673,
    139.6949,
    'Shibuya',
    'park-edge',
    'reset',
    'Open calm with city noise still hanging around it.',
    'Notice the first sound that proves this place is still Tokyo and not an escape hatch.',
    'Touch the gate, reset your breathing once, and get back to work.',
    'Bow to the park like it saved your life, then leave before anyone clocks you.',
    20,
    true
  ),
  (
    (select id from pack_refs where slug = 'tokyo'),
    'tokyo-nakameguro-tracks',
    'Nakameguro Under Tracks',
    35.6442,
    139.6986,
    'Meguro',
    'underpass',
    'tight',
    'Tight lanes, side-glances, and no wasted motion.',
    'Find one detail under the tracks that feels more night ride than daytime city.',
    'Read the lane, trust the line, and keep your cadence cleaner than the street deserves.',
    'Quietly rate the whole block out of ten with full confidence and absolutely no evidence.',
    30,
    true
  ),
  (
    (select id from pack_refs where slug = 'tokyo'),
    'tokyo-akihabara-udx',
    'Akihabara UDX Edge',
    35.7006,
    139.772,
    'Chiyoda',
    'district-edge',
    'neon-pressure',
    'Neon pressure, layered traffic, zero softness.',
    'Clock the exact point where commuter energy flips into full weirdness.',
    'Touch the edge, cut the noise, and move before the lights start bossing you around.',
    'Name your bike like it is an anime side character and roll to the next stop.',
    40,
    true
  ),
  (
    (select id from pack_refs where slug = 'tokyo'),
    'tokyo-ryogoku-river',
    'Ryogoku River Walk Drop',
    35.6962,
    139.7934,
    'Sumida',
    'river-edge',
    'wind-reset',
    'Waterline reset, but never fully relaxed.',
    'Notice what changes in the wind and decide if it helped or insulted you.',
    'Use the river as a reset seam, then snap back into the grid with intent.',
    'Throw one fake championship nod at the water and act like you just defended a title.',
    50,
    true
  ),
  (
    (select id from pack_refs where slug = 'tokyo'),
    'tokyo-odaiba-decks',
    'Odaiba Decks Cut',
    35.6275,
    139.7753,
    'Odaiba',
    'bay-edge',
    'wide-trap',
    'Wide views, awkward edges, too much temptation to coast.',
    'Find the least postcard-worthy angle and trust it more than the obvious one.',
    'Touch the deck zone, skip the view trap, and get moving again.',
    'Give the skyline a sarcastic compliment under your breath and disappear before it answers back.',
    60,
    true
  )
on conflict (slug) do update
set
  pack_id = excluded.pack_id,
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  district = excluded.district,
  category = excluded.category,
  vibe = excluded.vibe,
  hint = excluded.hint,
  task_local = excluded.task_local,
  task_fast = excluded.task_fast,
  task_chaotic = excluded.task_chaotic,
  sort_weight = excluded.sort_weight,
  is_active = excluded.is_active,
  updated_at = now();
